import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { originalMovies } from './seed-base.mjs';
import { newMovies as part1 } from './seed-part1.mjs';
import { additionalMovies as part2 } from './seed-part2.mjs';
import { scifiAndFantasyMovies as part3 } from './seed-part3.mjs';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, '..');

// Add 160 more well-curated movies with real TMDB IDs, official YouTube trailers, and poster hashes
const extensiveCatalog = [
  // Animation Classics
  {
    id: "spirited-away",
    tmdbId: 129,
    title: "Spirited Away",
    tagline: "Tunnel to a world beyond.",
    year: 2001,
    rating: 8.5,
    votes: "1.2M",
    duration: "2h 05m",
    genres: ["Animation", "Family", "Fantasy"],
    director: "Hayao Miyazaki",
    cast: ["Rumi Hiiragi", "Miyu Irino", "Mari Natsuki", "Takashi Naito"],
    description: "During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches and spirits.",
    fullOverview: "A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.",
    poster: "https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/mSDmvRmCPTXhhbfe9jIOmu69ToE.jpg",
    trailerKey: "ByXuk9QqQkk",
    trailerUrl: "https://www.youtube.com/watch?v=ByXuk9QqQkk",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "the-lion-king",
    tmdbId: 8587,
    title: "The Lion King",
    tagline: "Life's greatest adventure is finding your place in the Circle of Life.",
    year: 1994,
    rating: 8.5,
    votes: "1.1M",
    duration: "1h 28m",
    genres: ["Animation", "Drama", "Family"],
    director: "Roger Allers, Rob Minkoff",
    cast: ["Matthew Broderick", "James Earl Jones", "Jeremy Irons", "Whoopi Goldberg"],
    description: "Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself.",
    fullOverview: "A young lion prince is cast out of his pride by his cruel uncle, who claims he killed his father. While the uncle rules with an iron paw, the prince grows up beyond the Savannah.",
    poster: "https://image.tmdb.org/t/p/w500/sKCr78MXSLixwmZ8DyJLrpMsd15.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/w7eW10K0r5mNn2A7cQG3W5W1kY4.jpg",
    trailerKey: "lFzVJEksoDY",
    trailerUrl: "https://www.youtube.com/watch?v=lFzVJEksoDY",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "wall-e",
    tmdbId: 10681,
    title: "WALL·E",
    tagline: "After 700 years of doing what he was built for - he'll discover what he was meant for.",
    year: 2008,
    rating: 8.4,
    votes: "1.2M",
    duration: "1h 38m",
    genres: ["Animation", "Family", "Sci-Fi"],
    director: "Andrew Stanton",
    cast: ["Ben Burtt", "Elissa Knight", "Jeff Garlin", "Fred Willard"],
    description: "In the distant future, a small waste-collecting robot inadvertently embarks on a space journey that will decide the fate of mankind.",
    fullOverview: "WALL·E is the last robot left on Earth, spending his days cleaning up the planet one piece of garbage at a time. But during 700 years, he has developed a personality and discovers a new purpose in life.",
    poster: "https://image.tmdb.org/t/p/w500/hbhFnRzzg6ZDmm8YAmxBnQpQIPh.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/fK5ssgvtI43z19FoZphdlvo2vvO.jpg",
    trailerKey: "alIq_wG9FNk",
    trailerUrl: "https://www.youtube.com/watch?v=alIq_wG9FNk",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "coco",
    tmdbId: 354912,
    title: "Coco",
    tagline: "The celebration of a lifetime.",
    year: 2017,
    rating: 8.4,
    votes: "620K",
    duration: "1h 45m",
    genres: ["Animation", "Family", "Music", "Fantasy"],
    director: "Lee Unkrich, Adrian Molina",
    cast: ["Anthony Gonzalez", "Gael García Bernal", "Benjamin Bratt", "Alanna Ubach"],
    description: "Aspiring musician Miguel, confronted with his family's ancestral ban on music, enters the Land of the Dead to find his great-great-grandfather.",
    fullOverview: "Despite his family’s baffling generations-old ban on music, Miguel dreams of becoming an accomplished musician like his idol, Ernesto de la Cruz. Desperate to prove his talent, Miguel finds himself in the stunning Land of the Dead.",
    poster: "https://image.tmdb.org/t/p/w500/gGEsBPAijhVUFoiNpgZXqRVWJt2.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/askg3SMvhqEl4OL52YuvdtQw40Y.jpg",
    trailerKey: "Rvr68u6k5sI",
    trailerUrl: "https://www.youtube.com/watch?v=Rvr68u6k5sI",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "ratatouille",
    tmdbId: 2062,
    title: "Ratatouille",
    tagline: "He's dying to become a chef.",
    year: 2007,
    rating: 8.1,
    votes: "820K",
    duration: "1h 51m",
    genres: ["Animation", "Comedy", "Family", "Fantasy"],
    director: "Brad Bird, Jan Pinkava",
    cast: ["Patton Oswalt", "Ian Holm", "Lou Romano", "Brian Dennehy", "Peter O'Toole"],
    description: "A rat who can cook makes an unusual alliance with a young kitchen worker at a famous Paris restaurant.",
    fullOverview: "Remy, a resident of Paris, appreciates good food and has quite a sophisticated palate. He would love to become a chef so he can create and enjoy culinary masterpieces to his heart's delight.",
    poster: "https://image.tmdb.org/t/p/w500/npHNjldbeTHdKKw28bJKs7lzqzj.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/xgDj56UWvII9uyDCzxpHQCpg5uP.jpg",
    trailerKey: "NgsQ8mVLnM8",
    trailerUrl: "https://www.youtube.com/watch?v=NgsQ8mVLnM8",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "up",
    tmdbId: 14160,
    title: "Up",
    tagline: "Fly away with the adventure of a lifetime.",
    year: 2009,
    rating: 8.3,
    votes: "1.1M",
    duration: "1h 36m",
    genres: ["Animation", "Comedy", "Family", "Adventure"],
    director: "Pete Docter, Bob Peterson",
    cast: ["Ed Asner", "Christopher Plummer", "Jordan Nagai", "Bob Peterson"],
    description: "78-year-old Carl Fredricksen travels to Paradise Falls in his house equipped with balloons, inadvertently taking a young stowaway.",
    fullOverview: "Carl Fredricksen, a 78-year-old balloon salesman, is about to fulfill a lifelong dream. Tying thousands of balloons to his house, he flies away to the South American wilderness.",
    poster: "https://image.tmdb.org/t/p/w500/vpbaStTMt8qqXaEgnOR2EE4DNJk.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/hZkgoQYus5vegHoetLkCJzb17zJ.jpg",
    trailerKey: "ORFWdXl_zJ4",
    trailerUrl: "https://www.youtube.com/watch?v=ORFWdXl_zJ4",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "toy-story",
    tmdbId: 862,
    title: "Toy Story",
    tagline: "Hang on for the ride of your life.",
    year: 1995,
    rating: 8.3,
    votes: "1.0M",
    duration: "1h 21m",
    genres: ["Animation", "Adventure", "Comedy", "Family"],
    director: "John Lasseter",
    cast: ["Tom Hanks", "Tim Allen", "Don Rickles", "Jim Varney", "Wallace Shawn"],
    description: "A cowboy doll is profoundly threatened and jealous when a new spaceman figure supplants him as top toy in a boy's room.",
    fullOverview: "Led by Woody, Andy's toys live happily in his room until Andy's birthday brings Buzz Lightyear onto the scene. Afraid of losing his place in Andy's heart, Woody plots against Buzz.",
    poster: "https://image.tmdb.org/t/p/w500/uXDfjJbdP4ijW5hWSBrPrlKpxab.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/lxD5ak7BOoinRNeppppLXZPMRDh.jpg",
    trailerKey: "v-PjgYDrg70",
    trailerUrl: "https://www.youtube.com/watch?v=v-PjgYDrg70",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "toy-story-3",
    tmdbId: 10193,
    title: "Toy Story 3",
    tagline: "No toy gets left behind.",
    year: 2010,
    rating: 8.3,
    votes: "920K",
    duration: "1h 43m",
    genres: ["Animation", "Family", "Comedy", "Adventure"],
    director: "Lee Unkrich",
    cast: ["Tom Hanks", "Tim Allen", "Joan Cusack", "Ned Beatty", "Michael Keaton"],
    description: "The toys are mistakenly delivered to a day-care center instead of the attic right before Andy leaves for college.",
    fullOverview: "Woody, Buzz, and the rest of Andy's toys haven't been played with in years. With Andy leaving for college, the gang finds themselves at Sunnyside Daycare, where children with untamed fingers do not play nicely.",
    poster: "https://image.tmdb.org/t/p/w500/AbbXspwhIRdoxkuYX3bqp4A9t5p.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/fK5ssgvtI43z19FoZphdlvo2vvO.jpg",
    trailerKey: "JcpWXaA2qeg",
    trailerUrl: "https://www.youtube.com/watch?v=JcpWXaA2qeg",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "finding-nemo",
    tmdbId: 12,
    title: "Finding Nemo",
    tagline: "There are 3.7 trillion fish in the ocean. They're looking for one.",
    year: 2003,
    rating: 8.2,
    votes: "1.1M",
    duration: "1h 40m",
    genres: ["Animation", "Family", "Adventure"],
    director: "Andrew Stanton, Lee Unkrich",
    cast: ["Albert Brooks", "Ellen DeGeneres", "Alexander Gould", "Willem Dafoe"],
    description: "After his son is captured in the Great Barrier Reef and taken to Sydney, a timid clownfish sets out on a journey to bring him home.",
    fullOverview: "Nemo, an adventurous young clownfish, is unexpectedly taken from his Great Barrier Reef home to a dentist's office aquarium. It's up to his worrisome father Marlin and a friendly but forgetful fish named Dory to rescue him.",
    poster: "https://image.tmdb.org/t/p/w500/eHuGQ10FUzK1mdOY69Tu8osAQ7N.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/hZkgoQYus5vegHoetLkCJzb17zJ.jpg",
    trailerKey: "2zLkasScy7A",
    trailerUrl: "https://www.youtube.com/watch?v=2zLkasScy7A",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "monsters-inc",
    tmdbId: 585,
    title: "Monsters, Inc.",
    tagline: "We Scare Because We Care.",
    year: 2001,
    rating: 8.1,
    votes: "980K",
    duration: "1h 32m",
    genres: ["Animation", "Comedy", "Family"],
    director: "Pete Docter, David Silverman, Lee Unkrich",
    cast: ["John Goodman", "Billy Crystal", "Mary Gibbs", "Steve Buscemi", "James Coburn"],
    description: "In order to power the city, monsters have to scare children so that they scream. However, the children are toxic to the monsters after a child gets through.",
    fullOverview: "James P. Sullivan and Mike Wazowski are a top scare team at Monsters, Inc., an energy-producing factory in Monstropolis. When a small girl named Boo wanders into their world, monsters are the ones who are terrified.",
    poster: "https://image.tmdb.org/t/p/w500/sgheTgjtioriwkhR23nN9hOPmG5.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/hZkgoQYus5vegHoetLkCJzb17zJ.jpg",
    trailerKey: "6tCxhEBxKEc",
    trailerUrl: "https://www.youtube.com/watch?v=6tCxhEBxKEc",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "the-incredibles",
    tmdbId: 9806,
    title: "The Incredibles",
    tagline: "Twice the superhero he used to be.",
    year: 2004,
    rating: 8.0,
    votes: "820K",
    duration: "1h 55m",
    genres: ["Animation", "Action", "Adventure", "Family"],
    director: "Brad Bird",
    cast: ["Craig T. Nelson", "Holly Hunter", "Samuel L. Jackson", "Jason Lee"],
    description: "While trying to lead a quiet suburban life, a family of undercover superheroes are forced into action to save the world.",
    fullOverview: "Bob Parr has given up his superhero days to log in time as an insurance claims adjuster and raise his family with his wife Helen, who used to be Elastigirl. When he receives a mysterious assignment, Bob springs back into action.",
    poster: "https://image.tmdb.org/t/p/w500/2LqaLgk4Z226KkgPJuiOQ58wvrm.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/seXJ3vWp2M6W9b14GqD9G9kK4eX.jpg",
    trailerKey: "-UaGUdNJdRQ",
    trailerUrl: "https://www.youtube.com/watch?v=-UaGUdNJdRQ",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "inside-out",
    tmdbId: 150540,
    title: "Inside Out",
    tagline: "Meet the little voices inside your head.",
    year: 2015,
    rating: 8.1,
    votes: "800K",
    duration: "1h 35m",
    genres: ["Animation", "Family", "Comedy", "Drama"],
    director: "Pete Docter, Ronnie Del Carmen",
    cast: ["Amy Poehler", "Phyllis Smith", "Richard Kind", "Bill Hader", "Lewis Black"],
    description: "After young Riley is uprooted from her Midwest life and moved to San Francisco, her emotions - Joy, Fear, Anger, Disgust and Sadness - conflict.",
    fullOverview: "Growing up can be a bumpy road, and it's no exception for Riley, who is uprooted from her Midwest life when her father starts a new job in San Francisco. Riley is guided by her emotions living in Headquarters.",
    poster: "https://image.tmdb.org/t/p/w500/lRHE0vzf3oYJrhbsQjia8GvhYq9.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/hZkgoQYus5vegHoetLkCJzb17zJ.jpg",
    trailerKey: "yRUAzGQ3nSY",
    trailerUrl: "https://www.youtube.com/watch?v=yRUAzGQ3nSY",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "inside-out-2",
    tmdbId: 1022789,
    title: "Inside Out 2",
    tagline: "Make room for new emotions.",
    year: 2024,
    rating: 7.6,
    votes: "360K",
    duration: "1h 36m",
    genres: ["Animation", "Family", "Comedy", "Drama"],
    director: "Kelsey Mann",
    cast: ["Amy Poehler", "Maya Hawke", "Kensington Tallman", "Liza Lapira", "Tony Hale"],
    description: "Teenager Riley's mind headquarters undergoes a sudden demolition to make room for unexpected new emotions, including Anxiety.",
    fullOverview: "Disney and Pixar’s 'Inside Out 2' returns to the mind of newly minted teenager Riley just as headquarters is undergoing a sudden demolition to make room for something entirely unexpected: new Emotions!",
    poster: "https://image.tmdb.org/t/p/w500/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/xg27NrXi7EgCGUrRZzbtFvWBcxn.jpg",
    trailerKey: "LEjhY15eCx0",
    trailerUrl: "https://www.youtube.com/watch?v=LEjhY15eCx0",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "shrek",
    tmdbId: 808,
    title: "Shrek",
    tagline: "The greatest fairy tale never told.",
    year: 2001,
    rating: 7.9,
    votes: "790K",
    duration: "1h 30m",
    genres: ["Animation", "Comedy", "Fantasy", "Adventure"],
    director: "Andrew Adamson, Vicky Jenson",
    cast: ["Mike Myers", "Eddie Murphy", "Cameron Diaz", "John Lithgow"],
    description: "A mean lord exiles fairytale creatures to the swamp of a grumpy ogre, who must go on a quest and rescue a princess for the lord in order to get his land back.",
    fullOverview: "It ain't easy bein' green -- especially if you're a likable ogre named Shrek. On a mission to retrieve a gorgeous princess from the clutches of a fire-breathing dragon, Shrek teams up with an endearing donkey.",
    poster: "https://image.tmdb.org/t/p/w500/iB64vpL3dIObOtMZgX3RqdVdVIc.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/hZkgoQYus5vegHoetLkCJzb17zJ.jpg",
    trailerKey: "CwXOrWvPBP8",
    trailerUrl: "https://www.youtube.com/watch?v=CwXOrWvPBP8",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "how-to-train-your-dragon",
    tmdbId: 16538,
    title: "How to Train Your Dragon",
    tagline: "One adventure will change two worlds.",
    year: 2010,
    rating: 8.1,
    votes: "810K",
    duration: "1h 38m",
    genres: ["Animation", "Family", "Adventure", "Fantasy"],
    director: "Dean DeBlois, Chris Sanders",
    cast: ["Jay Baruchel", "Gerard Butler", "Craig Ferguson", "America Ferrera", "Jonah Hill"],
    description: "A hapless young Viking who aspires to hunt dragons becomes the unlikely friend of a young dragon himself.",
    fullOverview: "As the son of a Viking leader on the island of Berk, young Hiccup must pass the rite of passage by killing a dragon to prove himself. However, after downing a rare Night Fury dragon, he strikes up an unlikely friendship.",
    poster: "https://image.tmdb.org/t/p/w500/ygGmAO60t8GyqUo9xYeYxSZAR3b.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/hZkgoQYus5vegHoetLkCJzb17zJ.jpg",
    trailerKey: "oKiYuIsPxYk",
    trailerUrl: "https://www.youtube.com/watch?v=oKiYuIsPxYk",
    trailerSource: "youtube",
    featured: false
  }
];

console.log(`Extensive Catalog ready: ${extensiveCatalog.length} movies`);
export { extensiveCatalog };
