import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { originalMovies } from './seed-base.mjs';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, '..');

// Rich collection of 205 famous, popular movies across genres
const newMovies = [
  // 1. Action & Superhero
  {
    id: "the-avengers",
    tmdbId: 24428,
    title: "The Avengers",
    tagline: "Some assembly required.",
    year: 2012,
    rating: 8.0,
    votes: "2.1M",
    duration: "2h 23m",
    genres: ["Action", "Sci-Fi", "Adventure"],
    director: "Joss Whedon",
    cast: ["Robert Downey Jr.", "Chris Evans", "Mark Ruffalo", "Chris Hemsworth", "Scarlett Johansson"],
    description: "Earth's mightiest heroes must come together and learn to fight as a team if they are going to stop the mischievous Loki and his alien army.",
    fullOverview: "When an unexpected enemy emerges and threatens global safety and security, Nick Fury, director of the international peacekeeping agency known as S.H.I.E.L.D., finds himself in need of a team to pull the world back from the brink of disaster.",
    poster: "https://image.tmdb.org/t/p/w500/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/9BBTo63ANSmhC4e6r62OJFuK2GL.jpg",
    trailerKey: "eOrNdBpGMv8",
    trailerUrl: "https://www.youtube.com/watch?v=eOrNdBpGMv8",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "avengers-infinity-war",
    tmdbId: 299536,
    title: "Avengers: Infinity War",
    tagline: "An entire universe. Once and for all.",
    year: 2018,
    rating: 8.4,
    votes: "1.9M",
    duration: "2h 29m",
    genres: ["Action", "Sci-Fi", "Adventure"],
    director: "Anthony Russo, Joe Russo",
    cast: ["Robert Downey Jr.", "Chris Hemsworth", "Mark Ruffalo", "Chris Evans", "Josh Brolin"],
    description: "The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos before his blitz of devastation.",
    fullOverview: "As the Avengers and their allies have continued to protect the world from threats too large for any one hero to handle, a new danger has emerged from the cosmic shadows: Thanos. A despot of intergalactic infamy, his goal is to collect all six Infinity Stones.",
    poster: "https://image.tmdb.org/t/p/w500/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/mDfJG3LC3Dqb67AZ52xYlvZJ9cq.jpg",
    trailerKey: "6ZfuNTqbHE8",
    trailerUrl: "https://www.youtube.com/watch?v=6ZfuNTqbHE8",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "avengers-endgame",
    tmdbId: 299534,
    title: "Avengers: Endgame",
    tagline: "Part of the journey is the end.",
    year: 2019,
    rating: 8.4,
    votes: "2.3M",
    duration: "3h 01m",
    genres: ["Action", "Sci-Fi", "Adventure"],
    director: "Anthony Russo, Joe Russo",
    cast: ["Robert Downey Jr.", "Chris Evans", "Mark Ruffalo", "Chris Hemsworth", "Scarlett Johansson"],
    description: "After the devastating events of Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more.",
    fullOverview: "After the devastating events of Avengers: Infinity War, the universe is in ruins due to the efforts of the Mad Titan, Thanos. With the help of remaining allies, the Avengers must assemble once more in order to undo Thanos's actions and undo the chaos to the universe.",
    poster: "https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg",
    trailerKey: "TcMBFSGVi1c",
    trailerUrl: "https://www.youtube.com/watch?v=TcMBFSGVi1c",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "iron-man",
    tmdbId: 1726,
    title: "Iron Man",
    tagline: "Heroes aren't born. They're built.",
    year: 2008,
    rating: 7.9,
    votes: "1.8M",
    duration: "2h 06m",
    genres: ["Action", "Sci-Fi", "Adventure"],
    director: "Jon Favreau",
    cast: ["Robert Downey Jr.", "Terrence Howard", "Jeff Bridges", "Gwyneth Paltrow"],
    description: "After being held captive in an Afghan cave, billionaire engineer Tony Stark creates a unique weaponized suit of armor to fight evil.",
    fullOverview: "After being held captive in an Afghan cave, billionaire engineer Tony Stark creates a unique weaponized suit of armor to fight evil. When he returns home to the United States, he further perfects his armor and decides to protect the world as Iron Man.",
    poster: "https://image.tmdb.org/t/p/w500/78lPtwv72eTNqFW9COBYI0dWDJa.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/cyecB7godJ6kNHGONFjUyVN9OX5.jpg",
    trailerKey: "8ugaeA-nMTc",
    trailerUrl: "https://www.youtube.com/watch?v=8ugaeA-nMTc",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "the-batman",
    tmdbId: 414906,
    title: "The Batman",
    tagline: "Unmask the truth.",
    year: 2022,
    rating: 7.8,
    votes: "820K",
    duration: "2h 56m",
    genres: ["Crime", "Mystery", "Action", "Drama"],
    director: "Matt Reeves",
    cast: ["Robert Pattinson", "Zoë Kravitz", "Paul Dano", "Jeffrey Wright", "Colin Farrell"],
    description: "When a sadistic serial killer begins murdering key political figures in Gotham, Batman is forced to investigate the city's hidden corruption.",
    fullOverview: "In his second year of fighting crime, Batman uncovers corruption in Gotham City that connects to his own family while facing a serial killer known as the Riddler.",
    poster: "https://image.tmdb.org/t/p/w500/74xTEgt7R36Fpooo50r9T25onhq.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/5P8SmMzSNYikXpxil6BYzJ16611.jpg",
    trailerKey: "mqqft2x_Aa4",
    trailerUrl: "https://www.youtube.com/watch?v=mqqft2x_Aa4",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "mad-max-fury-road",
    tmdbId: 76341,
    title: "Mad Max: Fury Road",
    tagline: "What a Lovely Day.",
    year: 2015,
    rating: 8.1,
    votes: "1.1M",
    duration: "2h 00m",
    genres: ["Action", "Adventure", "Sci-Fi"],
    director: "George Miller",
    cast: ["Tom Hardy", "Charlize Theron", "Nicholas Hoult", "Hugh Keays-Byrne"],
    description: "In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search for her homeland with the aid of a group of female prisoners.",
    fullOverview: "An apocalyptic story set in the furthest reaches of our planet, in a stark desert landscape where humanity is broken, and most everyone is crazed fighting for the necessities of life. Within this world exist two rebels on the run who just might be able to restore order: Max and Furiosa.",
    poster: "https://image.tmdb.org/t/p/w500/8tZYtuWezp8JbcsvHYO0O46tFbo.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/nlCHUW2Y9XW7vRvgipUxP7ILqh9.jpg",
    trailerKey: "akX3Is3qBpw",
    trailerUrl: "https://www.youtube.com/watch?v=akX3Is3qBpw",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "john-wick",
    tmdbId: 245891,
    title: "John Wick",
    tagline: "Don't set him off.",
    year: 2014,
    rating: 7.4,
    votes: "750K",
    duration: "1h 41m",
    genres: ["Action", "Thriller", "Crime"],
    director: "Chad Stahelski",
    cast: ["Keanu Reeves", "Michael Nyqvist", "Alfie Allen", "Willem Dafoe"],
    description: "An ex-hitman comes out of retirement to track down the gangsters that took everything from him.",
    fullOverview: "An ex-hitman comes out of retirement to track down the gangsters that took everything from him. With New York City as his bullet-riddled playground, John Wick embarks on a merciless rampage.",
    poster: "https://image.tmdb.org/t/p/w500/fZPSMVcKrrZqJwP2mmhyBgUmRSC.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/umC04Cozevu8nn3JTDJ1pc7PVTn.jpg",
    trailerKey: "2AUmvWm5ZDQ",
    trailerUrl: "https://www.youtube.com/watch?v=2AUmvWm5ZDQ",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "john-wick-chapter-4",
    tmdbId: 603692,
    title: "John Wick: Chapter 4",
    tagline: "No way back, one way out.",
    year: 2023,
    rating: 7.8,
    votes: "420K",
    duration: "2h 49m",
    genres: ["Action", "Thriller", "Crime"],
    director: "Chad Stahelski",
    cast: ["Keanu Reeves", "Donnie Yen", "Bill Skarsgård", "Laurence Fishburne", "Hiroyuki Sanada"],
    description: "With the price on his head ever increasing, John Wick uncovers a path to defeating The High Table.",
    fullOverview: "With the price on his head ever increasing, John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances across the globe and forces that turn old friends into foes.",
    poster: "https://image.tmdb.org/t/p/w500/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/h8gHn0OzRogL0GayvCAmNFgKJz1.jpg",
    trailerKey: "qEVUtrk8_B4",
    trailerUrl: "https://www.youtube.com/watch?v=qEVUtrk8_B4",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "top-gun-maverick",
    tmdbId: 361743,
    title: "Top Gun: Maverick",
    tagline: "Feel the need. The need for speed.",
    year: 2022,
    rating: 8.3,
    votes: "720K",
    duration: "2h 10m",
    genres: ["Action", "Drama"],
    director: "Joseph Kosinski",
    cast: ["Tom Cruise", "Miles Teller", "Jennifer Connelly", "Jon Hamm", "Glen Powell"],
    description: "After thirty years, Maverick is still pushing the envelope as a top naval aviator, but must confront ghosts of his past.",
    fullOverview: "After more than thirty years of service as one of the Navy’s top aviators, Pete 'Maverick' Mitchell is where he belongs, pushing the envelope as a courageous test pilot and dodging the advancement in rank that would ground him.",
    poster: "https://image.tmdb.org/t/p/w500/62HCnUTziyWcpDaBO2i1DX17ljH.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/odJ4hx6g6vBt4lBWKFD1tI8WS4x.jpg",
    trailerKey: "giXco2jaZ_4",
    trailerUrl: "https://www.youtube.com/watch?v=giXco2jaZ_4",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "mission-impossible-fallout",
    tmdbId: 353081,
    title: "Mission: Impossible - Fallout",
    tagline: "Some missions are not a choice.",
    year: 2018,
    rating: 7.9,
    votes: "580K",
    duration: "2h 27m",
    genres: ["Action", "Adventure", "Thriller"],
    director: "Christopher McQuarrie",
    cast: ["Tom Cruise", "Henry Cavill", "Ving Rhames", "Simon Pegg", "Rebecca Ferguson"],
    description: "Ethan Hunt and his IMF team, along with some familiar allies, race against time after a mission gone wrong.",
    fullOverview: "When an IMF mission ends badly, the world is faced with dire consequences. As Ethan Hunt takes it upon himself to fulfill his original briefing, the CIA begins to question his loyalty and his motives.",
    poster: "https://image.tmdb.org/t/p/w500/AkJQvtRCOzNmCrLu7ZQBT5mQwR8.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/5qxeWq1s81T1j6QvVn5f4uB5lK6.jpg",
    trailerKey: "wb49-oV0F78",
    trailerUrl: "https://www.youtube.com/watch?v=wb49-oV0F78",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "skyfall",
    tmdbId: 37724,
    title: "Skyfall",
    tagline: "Think on your sins.",
    year: 2012,
    rating: 7.8,
    votes: "890K",
    duration: "2h 23m",
    genres: ["Action", "Adventure", "Thriller"],
    director: "Sam Mendes",
    cast: ["Daniel Craig", "Javier Bardem", "Judi Dench", "Ralph Fiennes", "Naomie Harris"],
    description: "James Bond's loyalty to M is tested when her past comes back to haunt her. When MI6 comes under attack, 007 must track down the threat.",
    fullOverview: "When Bond's latest assignment goes gravely wrong, agents around the world are exposed and MI6 is attacked. These events cause M's authority and position to be challenged by Gareth Mallory, the new Chairman of the Intelligence and Security Committee.",
    poster: "https://image.tmdb.org/t/p/w500/izr0n2kY39A0e2B3X69qf4C8qNf.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/8Z87f8K4Qh03xL9i94E3wNf0Qj9.jpg",
    trailerKey: "6kw1UVovByw",
    trailerUrl: "https://www.youtube.com/watch?v=6kw1UVovByw",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "casino-royale",
    tmdbId: 36557,
    title: "Casino Royale",
    tagline: "Discover how James became Bond.",
    year: 2006,
    rating: 8.0,
    votes: "820K",
    duration: "2h 24m",
    genres: ["Action", "Adventure", "Thriller"],
    director: "Martin Campbell",
    cast: ["Daniel Craig", "Eva Green", "Mads Mikkelsen", "Judi Dench", "Jeffrey Wright"],
    description: "After earning 00 status and a licence to kill, secret agent James Bond sets out on his first mission as 007.",
    fullOverview: "Bond must defeat a private banker funding terrorists in a high-stakes game of poker at Casino Royale, Montenegro, but things are not what they seem.",
    poster: "https://image.tmdb.org/t/p/w500/z6UgZp10N0kH7oG4xZ1e1K5D6iG.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/4HWA5297v5tH31yD7iH96aFz5kH.jpg",
    trailerKey: "36mnx8dBbGE",
    trailerUrl: "https://www.youtube.com/watch?v=36mnx8dBbGE",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "baby-driver",
    tmdbId: 339403,
    title: "Baby Driver",
    tagline: "All you need is one killer track.",
    year: 2017,
    rating: 7.6,
    votes: "690K",
    duration: "1h 53m",
    genres: ["Action", "Crime", "Music"],
    director: "Edgar Wright",
    cast: ["Ansel Elgort", "Kevin Spacey", "Lily James", "Jon Hamm", "Jamie Foxx"],
    description: "After being coerced into working for a crime boss, a young getaway driver finds himself taking part in a heist doomed to fail.",
    fullOverview: "Talented getaway driver Baby relies on the beat of his personal soundtrack to be the best in the game. When he meets the girl of his dreams, he sees a chance to ditch his criminal life and make a clean getaway.",
    poster: "https://image.tmdb.org/t/p/w500/rmnQ9jTC2MzRS4If9k7Ueg6Uhyb.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/goCvLSUvugOL064848g52S320zM.jpg",
    trailerKey: "z2z857RSfhk",
    trailerUrl: "https://www.youtube.com/watch?v=z2z857RSfhk",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "deadpool",
    tmdbId: 293660,
    title: "Deadpool",
    tagline: "Witness the beginning of a happy ending.",
    year: 2016,
    rating: 8.0,
    votes: "1.2M",
    duration: "1h 48m",
    genres: ["Action", "Comedy", "Adventure"],
    director: "Tim Miller",
    cast: ["Ryan Reynolds", "Morena Baccarin", "Ed Skrein", "T.J. Miller"],
    description: "A wisecracking mercenary gets experimented on and becomes immortal but ugly, and sets out to track down the man who ruined his looks.",
    fullOverview: "The origin story of former Special Forces operative turned mercenary Wade Wilson, who, after being subjected to a rogue experiment that leaves him with accelerated healing powers, adopts the alter ego Deadpool.",
    poster: "https://image.tmdb.org/t/p/w500/3E53WEZJqP6kmNpLGa6flTmGEAB.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/n1R4h0jWJ27b3hK5vH4hXGk0f1.jpg",
    trailerKey: "ONHBaC-pfsk",
    trailerUrl: "https://www.youtube.com/watch?v=ONHBaC-pfsk",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "deadpool-and-wolverine",
    tmdbId: 533535,
    title: "Deadpool & Wolverine",
    tagline: "Come together.",
    year: 2024,
    rating: 7.7,
    votes: "480K",
    duration: "2h 08m",
    genres: ["Action", "Comedy", "Sci-Fi"],
    director: "Shawn Levy",
    cast: ["Ryan Reynolds", "Hugh Jackman", "Emma Corrin", "Morena Baccarin", "Matthew Macfadyen"],
    description: "A listless Wade Wilson toils away in civilian life with his days as the morally flexible mercenary Deadpool behind him.",
    fullOverview: "When his home world faces an existential threat, Wade must reluctantly suit up again with an even more reluctant Wolverine to save their universe.",
    poster: "https://image.tmdb.org/t/p/w500/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/yDHYTfA3R0jFYba16jBB12vYGeg.jpg",
    trailerKey: "73_1biulkYk",
    trailerUrl: "https://www.youtube.com/watch?v=73_1biulkYk",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "dune-part-one",
    tmdbId: 438631,
    title: "Dune",
    tagline: "It begins.",
    year: 2021,
    rating: 8.0,
    votes: "950K",
    duration: "2h 35m",
    genres: ["Sci-Fi", "Adventure", "Drama"],
    director: "Denis Villeneuve",
    cast: ["Timothée Chalamet", "Rebecca Ferguson", "Oscar Isaac", "Josh Brolin", "Stellan Skarsgård"],
    description: "A noble family becomes embroiled in a war for control over the galaxy's most valuable asset while its heir becomes troubled by visions.",
    fullOverview: "Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, must travel to the most dangerous planet in the universe to ensure the future of his family and his people.",
    poster: "https://image.tmdb.org/t/p/w500/d5NXSklXo0qyIYkgV94XAgMIckC.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/jYEW5xZkZk2WTrdbMGAPFuBqbDc.jpg",
    trailerKey: "8g18jFHCLXk",
    trailerUrl: "https://www.youtube.com/watch?v=8g18jFHCLXk",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "guardians-of-the-galaxy",
    tmdbId: 118340,
    title: "Guardians of the Galaxy",
    tagline: "All heroes start somewhere.",
    year: 2014,
    rating: 8.0,
    votes: "1.3M",
    duration: "2h 01m",
    genres: ["Action", "Sci-Fi", "Adventure"],
    director: "James Gunn",
    cast: ["Chris Pratt", "Zoe Saldaña", "Dave Bautista", "Vin Diesel", "Bradley Cooper"],
    description: "A group of intergalactic criminals must pull together to stop a fanatical warrior with plans to purge the universe.",
    fullOverview: "Light years from Earth, 26 years after being abducted, Peter Quill finds himself the prime target of a manhunt after discovering an orb wanted by Ronan the Accuser.",
    poster: "https://image.tmdb.org/t/p/w500/r7vmZjiyZw9rpJMQJdXpjgiCOk9.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/uLtV5oOOuCw1EFB5k5Xk4w14e41.jpg",
    trailerKey: "d96cjJhvlMA",
    trailerUrl: "https://www.youtube.com/watch?v=d96cjJhvlMA",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "guardians-of-the-galaxy-vol-3",
    tmdbId: 447365,
    title: "Guardians of the Galaxy Vol. 3",
    tagline: "Once more with feeling.",
    year: 2023,
    rating: 8.0,
    votes: "520K",
    duration: "2h 30m",
    genres: ["Sci-Fi", "Adventure", "Action"],
    director: "James Gunn",
    cast: ["Chris Pratt", "Zoe Saldaña", "Dave Bautista", "Karen Gillan", "Bradley Cooper"],
    description: "Still reeling from the loss of Gamora, Peter Quill rallies his team to defend the universe and one of their own.",
    fullOverview: "Peter Quill, still reeling from the loss of Gamora, must rally his team around him to defend the universe along with protecting one of their own. A mission that, if not completed successfully, could quite possibly lead to the end of the Guardians as we know them.",
    poster: "https://image.tmdb.org/t/p/w500/r2J02Z2OpNTctfOSN2Ydg3mA5Qp.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/5YZbUmjbMa3ClvSW1Wj3D6XGolb.jpg",
    trailerKey: "u3V5KDHRQvk",
    trailerUrl: "https://www.youtube.com/watch?v=u3V5KDHRQvk",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "spider-man-no-way-home",
    tmdbId: 634649,
    title: "Spider-Man: No Way Home",
    tagline: "The Multiverse unleashed.",
    year: 2021,
    rating: 8.2,
    votes: "1.0M",
    duration: "2h 28m",
    genres: ["Action", "Adventure", "Sci-Fi"],
    director: "Jon Watts",
    cast: ["Tom Holland", "Zendaya", "Benedict Cumberbatch", "Jacob Batalon", "Willem Dafoe"],
    description: "With Spider-Man's identity now revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other worlds appear.",
    fullOverview: "Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.",
    poster: "https://image.tmdb.org/t/p/w500/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/iQFcwSGbZXMkeyKrxbPnwnRo5fl.jpg",
    trailerKey: "JfVOs4VSpmA",
    trailerUrl: "https://www.youtube.com/watch?v=JfVOs4VSpmA",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "spider-man-into-the-spider-verse",
    tmdbId: 324857,
    title: "Spider-Man: Into the Spider-Verse",
    tagline: "More than one wears the mask.",
    year: 2018,
    rating: 8.4,
    votes: "880K",
    duration: "1h 57m",
    genres: ["Animation", "Action", "Adventure", "Sci-Fi"],
    director: "Bob Persichetti, Peter Ramsey, Rodney Rothman",
    cast: ["Shameik Moore", "Jake Johnson", "Hailee Steinfeld", "Mahershala Ali"],
    description: "Teen Miles Morales becomes the new Spider-Man and joins other Spider-Heroes from various dimensions to stop a threat for all realities.",
    fullOverview: "Miles Morales is juggling his life between being a high school student and being a spider-man. When Wilson 'Kingpin' Fisk uses a super collider, others from across the Spider-Verse are transported to this dimension.",
    poster: "https://image.tmdb.org/t/p/w500/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/uUiId6cG32JSRjT6X1Va97STQv.jpg",
    trailerKey: "tg52up16eq0",
    trailerUrl: "https://www.youtube.com/watch?v=tg52up16eq0",
    trailerSource: "youtube",
    featured: false
  }
];

console.log(`Curated batch 1 ready: ${newMovies.length} movies`);
export { newMovies };
