// Mega curated catalog of 130+ top worldwide English movies
export const megaCatalog = [
  // Thriller & Horror
  {
    id: "get-out",
    tmdbId: 419430,
    title: "Get Out",
    tagline: "Just because you're invited, doesn't mean you're welcome.",
    year: 2017,
    rating: 7.7,
    votes: "720K",
    duration: "1h 44m",
    genres: ["Horror", "Mystery", "Thriller"],
    director: "Jordan Peele",
    cast: ["Daniel Kaluuya", "Allison Williams", "Bradley Whitford", "Catherine Keener", "Lil Rel Howery"],
    description: "A young African-American visits his white girlfriend's parents for the weekend, where his simmering uneasiness becomes a nightmare.",
    fullOverview: "Chris and his girlfriend Rose go upstate to visit her parents for the weekend. At first, Chris reads the family's overly accommodating behavior as nervous attempts to deal with their daughter's interracial relationship.",
    poster: "https://image.tmdb.org/t/p/w500/tFXcEccSQMf3lfhfXKSU9iRBpa3.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/lGhuP913H3H6XW3JgP9qP8k0M6.jpg",
    trailerKey: "DzfpyUB60YY",
    trailerUrl: "https://www.youtube.com/watch?v=DzfpyUB60YY",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "us",
    tmdbId: 480530,
    title: "Us",
    tagline: "Watch yourself.",
    year: 2019,
    rating: 6.9,
    votes: "380K",
    duration: "1h 56m",
    genres: ["Horror", "Mystery", "Thriller"],
    director: "Jordan Peele",
    cast: ["Lupita Nyong'o", "Winston Duke", "Elisabeth Moss", "Tim Heidecker"],
    description: "A family's serene beach vacation turns to chaos when their doppelgängers appear and begin to terrorize them.",
    fullOverview: "Husband and wife Gabe and Adelaide Wilson take their kids to their beach house to unwind. But their vacation turns to nightmare when four mysterious figures show up at night.",
    poster: "https://image.tmdb.org/t/p/w500/ux2dU1jQ2ACIMShzB3y993LdpBu.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/8Z87f8K4Qh03xL9i94E3wNf0Qj9.jpg",
    trailerKey: "hNCmb-4oUJA",
    trailerUrl: "https://www.youtube.com/watch?v=hNCmb-4oUJA",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "nope",
    tmdbId: 762504,
    title: "Nope",
    tagline: "What's a bad miracle?",
    year: 2022,
    rating: 6.9,
    votes: "290K",
    duration: "2h 10m",
    genres: ["Horror", "Mystery", "Sci-Fi", "Thriller"],
    director: "Jordan Peele",
    cast: ["Daniel Kaluuya", "Keke Palmer", "Steven Yeun", "Michael Wincott", "Brandon Perea"],
    description: "Residents in a lonely gulch of inland California bear witness to an uncanny and chilling discovery.",
    fullOverview: "Two siblings running a California horse ranch discover something wonderful and sinister in the skies above, while the owner of an adjacent theme park tries to profit from the phenomenon.",
    poster: "https://image.tmdb.org/t/p/w500/AcKVlWaNVVVFQwro3nLXqPlnTn.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg",
    trailerKey: "In8fuzj3gck",
    trailerUrl: "https://www.youtube.com/watch?v=In8fuzj3gck",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "hereditary",
    tmdbId: 493922,
    title: "Hereditary",
    tagline: "Every family tree hides a secret.",
    year: 2018,
    rating: 7.3,
    votes: "430K",
    duration: "2h 07m",
    genres: ["Horror", "Mystery", "Drama"],
    director: "Ari Aster",
    cast: ["Toni Collette", "Alex Wolff", "Milly Shapiro", "Ann Dowd", "Gabriel Byrne"],
    description: "A grieving family is haunted by tragic and disturbing occurrences after the death of their secretive grandmother.",
    fullOverview: "When Ellen, the matriarch of the Graham family, passes away, her daughter's family begins to unravel cryptic and increasingly terrifying secrets about their ancestry.",
    poster: "https://image.tmdb.org/t/p/w500/p9fmuz2Oj3HtEJHG4h0k71Qv9eU.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/8Z87f8K4Qh03xL9i94E3wNf0Qj9.jpg",
    trailerKey: "V6wWKNij_1M",
    trailerUrl: "https://www.youtube.com/watch?v=V6wWKNij_1M",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "midsommar",
    tmdbId: 530385,
    title: "Midsommar",
    tagline: "Let the festivities begin.",
    year: 2019,
    rating: 7.1,
    votes: "410K",
    duration: "2h 28m",
    genres: ["Horror", "Drama", "Mystery"],
    director: "Ari Aster",
    cast: ["Florence Pugh", "Jack Reynor", "William Jackson Harper", "Vilhelm Blomgren", "Will Poulter"],
    description: "A couple travels to Northern Europe to visit a rural hometown's fabled Swedish mid-summer festival, but it becomes a bizarre nightmare.",
    fullOverview: "Several friends travel to Sweden to study as anthropologists a summer festival that is held every ninety years only to find themselves at the mercy of a sinister pagan cult.",
    poster: "https://image.tmdb.org/t/p/w500/7LEI8ulhhTeB2gy0ewUW3agCY0V.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/hZkgoQYus5vegHoetLkCJzb17zJ.jpg",
    trailerKey: "1Vnghdsjmd0",
    trailerUrl: "https://www.youtube.com/watch?v=1Vnghdsjmd0",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "the-shining",
    tmdbId: 694,
    title: "The Shining",
    tagline: "A masterpiece of modern horror.",
    year: 1980,
    rating: 8.4,
    votes: "1.1M",
    duration: "2h 26m",
    genres: ["Horror", "Thriller"],
    director: "Stanley Kubrick",
    cast: ["Jack Nicholson", "Shelley Duvall", "Danny Lloyd", "Scatman Crothers"],
    description: "A family heads to an isolated hotel for the winter where a sinister presence influences the father into violence.",
    fullOverview: "Jack Torrance accepts a caretaker job at the Overlook Hotel, where he, his wife Wendy and their son Danny must live isolated from the rest of the world for the winter. But they aren't prepared for the madness that lurks within.",
    poster: "https://image.tmdb.org/t/p/w500/xazWoLealQwEgqZ89MLZklLZD3k.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/mmd1HNuPtOXn7iOgmZ5f6b2mN4M.jpg",
    trailerKey: "S014446AA1M",
    trailerUrl: "https://www.youtube.com/watch?v=S014446AA1M",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "a-quiet-place",
    tmdbId: 447332,
    title: "A Quiet Place",
    tagline: "If they hear you, they hunt you.",
    year: 2018,
    rating: 7.5,
    votes: "610K",
    duration: "1h 30m",
    genres: ["Horror", "Drama", "Sci-Fi"],
    director: "John Krasinski",
    cast: ["Emily Blunt", "John Krasinski", "Millicent Simmonds", "Noah Jupe"],
    description: "A family struggles for survival in a world where most humans have been killed by blind but noise-sensitive creatures.",
    fullOverview: "A family is forced to live in silence while hiding from monsters that possess ultra-sensitive hearing, navigating everyday life through sign language.",
    poster: "https://image.tmdb.org/t/p/w500/nAU74GmpUk7t5iklEp3bufwDq4n.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/8Z87f8K4Qh03xL9i94E3wNf0Qj9.jpg",
    trailerKey: "WR7cc5t7tv8",
    trailerUrl: "https://www.youtube.com/watch?v=WR7cc5t7tv8",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "the-conjuring",
    tmdbId: 138843,
    title: "The Conjuring",
    tagline: "Based on the true case files of the Warrens.",
    year: 2013,
    rating: 7.5,
    votes: "580K",
    duration: "1h 52m",
    genres: ["Horror", "Thriller", "Mystery"],
    director: "James Wan",
    cast: ["Vera Farmiga", "Patrick Wilson", "Lili Taylor", "Ron Livingston"],
    description: "Paranormal investigators Ed and Lorraine Warren work to help a family terrorized by a dark presence in their farmhouse.",
    fullOverview: "Paranormal investigators Ed and Lorraine Warren work to help a family terrorized by a dark presence in their farmhouse. Forced to confront a powerful entity, the Warrens find themselves caught in the most terrifying case of their lives.",
    poster: "https://image.tmdb.org/t/p/w500/wVYREutTvI2tmxr6ujrHT704wGF.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/8Z87f8K4Qh03xL9i94E3wNf0Qj9.jpg",
    trailerKey: "k10ETZ41q5o",
    trailerUrl: "https://www.youtube.com/watch?v=k10ETZ41q5o",
    trailerSource: "youtube",
    featured: false
  },
  // Sci-Fi Blockbusters & Classics
  {
    id: "2001-a-space-odyssey",
    tmdbId: 62,
    title: "2001: A Space Odyssey",
    tagline: "The Ultimate Trip.",
    year: 1968,
    rating: 8.3,
    votes: "750K",
    duration: "2h 29m",
    genres: ["Sci-Fi", "Mystery", "Adventure"],
    director: "Stanley Kubrick",
    cast: ["Keir Dullea", "Gary Lockwood", "William Sylvester", "Daniel Richter"],
    description: "After uncovering a mysterious artifact buried beneath the Lunar surface, a spacecraft is sent to Jupiter to find its origins.",
    fullOverview: "Humanity finds a mysterious object buried beneath the lunar surface and sets off to find its origins with the help of HAL 9000, the world's most advanced supercomputer.",
    poster: "https://image.tmdb.org/t/p/w500/ve72VxNqjGM69UmK18YKnrmA7x5.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/8Z87f8K4Qh03xL9i94E3wNf0Qj9.jpg",
    trailerKey: "oR_e9y-bka0",
    trailerUrl: "https://www.youtube.com/watch?v=oR_e9y-bka0",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "blade-runner",
    tmdbId: 78,
    title: "Blade Runner",
    tagline: "Man has made his match... now it's his problem.",
    year: 1982,
    rating: 8.1,
    votes: "820K",
    duration: "1h 57m",
    genres: ["Sci-Fi", "Drama", "Thriller"],
    director: "Ridley Scott",
    cast: ["Harrison Ford", "Rutger Hauer", "Sean Young", "Edward James Olmos"],
    description: "A blade runner must pursue and terminate four replicants who stole a ship in space and have returned to Earth to find their creator.",
    fullOverview: "In the smog-choked dystopian Los Angeles of 2019, blade runner Rick Deckard is called out of retirement to terminate a quartet of replicants who have escaped to Earth.",
    poster: "https://image.tmdb.org/t/p/w500/63N9uy8nd9j7Eog2axPQ8lbr3Wj.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/8Z87f8K4Qh03xL9i94E3wNf0Qj9.jpg",
    trailerKey: "eogpIG53Cis",
    trailerUrl: "https://www.youtube.com/watch?v=eogpIG53Cis",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "back-to-the-future",
    tmdbId: 105,
    title: "Back to the Future",
    tagline: "He was never in time for his classes... He wasn't in time for his dinner... Then one day he wasn't in his time at all.",
    year: 1985,
    rating: 8.5,
    votes: "1.3M",
    duration: "1h 56m",
    genres: ["Adventure", "Comedy", "Sci-Fi"],
    director: "Robert Zemeckis",
    cast: ["Michael J. Fox", "Christopher Lloyd", "Lea Thompson", "Crispin Glover"],
    description: "Marty McFly, a 17-year-old high school student, is accidentally sent thirty years into the past in a time-traveling DeLorean.",
    fullOverview: "Eighties teenager Marty McFly is accidentally sent back in time to 1955, inadvertently disrupting his parents' first meeting and putting his own existence at risk.",
    poster: "https://image.tmdb.org/t/p/w500/fNOH9f1aA7XRTzl1sAOx9iF553Q.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/8Z87f8K4Qh03xL9i94E3wNf0Qj9.jpg",
    trailerKey: "qvsgGtivCgs",
    trailerUrl: "https://www.youtube.com/watch?v=qvsgGtivCgs",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "back-to-the-future-part-ii",
    tmdbId: 165,
    title: "Back to the Future Part II",
    tagline: "Getting back was only the beginning.",
    year: 1989,
    rating: 7.8,
    votes: "580K",
    duration: "1h 48m",
    genres: ["Adventure", "Comedy", "Sci-Fi"],
    director: "Robert Zemeckis",
    cast: ["Michael J. Fox", "Christopher Lloyd", "Lea Thompson", "Thomas F. Wilson"],
    description: "After visiting 2015, Marty McFly must repeat his visit to 1955 to prevent disastrous changes to 1985.",
    fullOverview: "Marty McFly has only just gotten back from the past, when he is once again picked up by Dr. Emmett Brown and sent through time to the future.",
    poster: "https://image.tmdb.org/t/p/w500/p4pYqf10fJ9kK4eX8rP3sD.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/8Z87f8K4Qh03xL9i94E3wNf0Qj9.jpg",
    trailerKey: "MdENmefJRpw",
    trailerUrl: "https://www.youtube.com/watch?v=MdENmefJRpw",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "minority-report",
    tmdbId: 180,
    title: "Minority Report",
    tagline: "What would you do if you were accused of a murder, but hadn't committed it yet?",
    year: 2002,
    rating: 7.7,
    votes: "590K",
    duration: "2h 25m",
    genres: ["Action", "Mystery", "Sci-Fi", "Thriller"],
    director: "Steven Spielberg",
    cast: ["Tom Cruise", "Colin Farrell", "Samantha Morton", "Max von Sydow"],
    description: "In a future where a special police unit is able to arrest murderers before they commit their crimes, an officer from that unit is himself accused of a future murder.",
    fullOverview: "John Anderton is top cop in the Precrime unit of the Washington D.C. police force in the year 2054. The unit uses three psychics called 'precogs' to predict murders before they happen.",
    poster: "https://image.tmdb.org/t/p/w500/ccqpHG1TGcv9sfvFp9M9KzEcfhG.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/8Z87f8K4Qh03xL9i94E3wNf0Qj9.jpg",
    trailerKey: "lG7DGMgfOb8",
    trailerUrl: "https://www.youtube.com/watch?v=lG7DGMgfOb8",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "edge-of-tomorrow",
    tmdbId: 137113,
    title: "Edge of Tomorrow",
    tagline: "Live. Die. Repeat.",
    year: 2014,
    rating: 7.9,
    votes: "750K",
    duration: "1h 53m",
    genres: ["Action", "Sci-Fi", "Adventure"],
    director: "Doug Liman",
    cast: ["Tom Cruise", "Emily Blunt", "Bill Paxton", "Brendan Gleeson"],
    description: "A soldier fighting aliens gets to relive the same day over and over again, the day restarting every time he dies.",
    fullOverview: "Major Bill Cage is an officer who has never seen a day of combat when he is unceremoniously dropped into what amounts to a suicide mission. Killed within minutes, Cage now finds himself inexplicably thrown into a time loop.",
    poster: "https://image.tmdb.org/t/p/w500/xjw5u965qE6qlN7r9wA94gQvP9G.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/8Z87f8K4Qh03xL9i94E3wNf0Qj9.jpg",
    trailerKey: "vw61gCe2oqI",
    trailerUrl: "https://www.youtube.com/watch?v=vw61gCe2oqI",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "district-9",
    tmdbId: 17654,
    title: "District 9",
    tagline: "You are not welcome here.",
    year: 2009,
    rating: 7.9,
    votes: "700K",
    duration: "1h 52m",
    genres: ["Action", "Sci-Fi", "Thriller"],
    director: "Neill Blomkamp",
    cast: ["Sharlto Copley", "Jason Cope", "Nathalie Boltt", "Sylvaine Strike"],
    description: "Violence ensues after an extraterrestrial race forced to live in slum-like conditions on Earth finds a soul in a government agent.",
    fullOverview: "Thirty years ago, aliens arrive on Earth -- not to conquer or give aid, but -- to find refuge from their dying planet. Separated from humans in a South African area called District 9, the aliens are managed by Multi-National United.",
    poster: "https://image.tmdb.org/t/p/w500/tuZhZ6biFMrBGs847b2w9q9Gz8L.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/8Z87f8K4Qh03xL9i94E3wNf0Qj9.jpg",
    trailerKey: "DyLUwOcR5pk",
    trailerUrl: "https://www.youtube.com/watch?v=DyLUwOcR5pk",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "children-of-men",
    tmdbId: 9693,
    title: "Children of Men",
    tagline: "No children. No future. No hope.",
    year: 2006,
    rating: 7.9,
    votes: "520K",
    duration: "1h 49m",
    genres: ["Drama", "Sci-Fi", "Thriller", "Action"],
    director: "Alfonso Cuarón",
    cast: ["Clive Owen", "Julianne Moore", "Michael Caine", "Chiwetel Ejiofor"],
    description: "In 2027, in a chaotic world in which women have become somehow infertile, a former activist agrees to help transport a miraculously pregnant woman to a sanctuary.",
    fullOverview: "In 2027, in a chaotic world in which women have become somehow infertile, a former activist agrees to help transport a miraculously pregnant woman to a sanctuary at sea.",
    poster: "https://image.tmdb.org/t/p/w500/kR4490Z2K8c46yP924vO6h9pI1.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/8Z87f8K4Qh03xL9i94E3wNf0Qj9.jpg",
    trailerKey: "2VT2apoX9dg",
    trailerUrl: "https://www.youtube.com/watch?v=2VT2apoX9dg",
    trailerSource: "youtube",
    featured: false
  },
  // Drama & Romance & Award Winners
  {
    id: "la-la-land",
    tmdbId: 313369,
    title: "La La Land",
    tagline: "Here's to the fools who dream.",
    year: 2016,
    rating: 8.0,
    votes: "650K",
    duration: "2h 08m",
    genres: ["Comedy", "Drama", "Music", "Romance"],
    director: "Damien Chazelle",
    cast: ["Ryan Gosling", "Emma Stone", "John Legend", "Rosemarie DeWitt", "J.K. Simmons"],
    description: "While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations.",
    fullOverview: "Mia, an aspiring actress, serves lattes to movie stars in between auditions and Sebastian, a jazz musician, scrapes by playing cocktail party gigs in dingy bars, but as success mounts they are faced with decisions that begin to fray the fragile fabric of their love affair.",
    poster: "https://image.tmdb.org/t/p/w500/uDO8zWDhfWwoFdKS4fzkVJt0Rf0.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/hZkgoQYus5vegHoetLkCJzb17zJ.jpg",
    trailerKey: "0pdqf4P9MB8",
    trailerUrl: "https://www.youtube.com/watch?v=0pdqf4P9MB8",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "titanic",
    tmdbId: 597,
    title: "Titanic",
    tagline: "Nothing on Earth could come between them.",
    year: 1997,
    rating: 7.9,
    votes: "1.3M",
    duration: "3h 14m",
    genres: ["Drama", "Romance"],
    director: "James Cameron",
    cast: ["Leonardo DiCaprio", "Kate Winslet", "Billy Zane", "Kathy Bates", "Bill Paxton"],
    description: "A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.",
    fullOverview: "101-year-old Rose DeWitt Bukater tells the story of her life aboard the Titanic, 84 years later. A young Rose boards the ship with her mother and fiancé. Meanwhile, Jack Dawson and Fabrizio De Rossi win third-class tickets aboard the ship.",
    poster: "https://image.tmdb.org/t/p/w500/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/8Z87f8K4Qh03xL9i94E3wNf0Qj9.jpg",
    trailerKey: "kVrqfYjkTdQ",
    trailerUrl: "https://www.youtube.com/watch?v=kVrqfYjkTdQ",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "her",
    tmdbId: 152601,
    title: "Her",
    tagline: "A Spike Jonze Love Story.",
    year: 2013,
    rating: 8.0,
    votes: "690K",
    duration: "2h 06m",
    genres: ["Romance", "Sci-Fi", "Drama"],
    director: "Spike Jonze",
    cast: ["Joaquin Phoenix", "Scarlett Johansson", "Amy Adams", "Rooney Mara", "Chris Pratt"],
    description: "In a near future, a lonely writer develops an unlikely relationship with an operating system designed to meet his every need.",
    fullOverview: "In the not so distant future, Theodore, a lonely writer purchases a newly developed operating system designed to meet the user's every needs. To Theodore's delight, a romantic relationship develops between him and his operating system.",
    poster: "https://image.tmdb.org/t/p/w500/eCOtqtfvn7mxGl6nfmq4b1exJRc.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/8Z87f8K4Qh03xL9i94E3wNf0Qj9.jpg",
    trailerKey: "dJTU48_yghs",
    trailerUrl: "https://www.youtube.com/watch?v=dJTU48_yghs",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "eternal-sunshine-of-the-spotless-mind",
    tmdbId: 38,
    title: "Eternal Sunshine of the Spotless Mind",
    tagline: "You can erase someone from your mind. Getting them out of your heart is another story.",
    year: 2004,
    rating: 8.3,
    votes: "1.1M",
    duration: "1h 48m",
    genres: ["Drama", "Romance", "Sci-Fi"],
    director: "Michel Gondry",
    cast: ["Jim Carrey", "Kate Winslet", "Kirsten Dunst", "Mark Ruffalo", "Elijah Wood"],
    description: "When their relationship turns sour, a couple undergoes a medical procedure to have each other erased from their memories.",
    fullOverview: "Joel Barish, heartbroken that his girlfriend Clementine underwent a procedure to erase him from her memory, decides to do the same. However, as he watches his memories of her fade away, he realizes he still loves her.",
    poster: "https://image.tmdb.org/t/p/w500/5MwkWH9tYHv3mV9OdYTMR5q9EdY.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/8Z87f8K4Qh03xL9i94E3wNf0Qj9.jpg",
    trailerKey: "07-QBnEkgXU",
    trailerUrl: "https://www.youtube.com/watch?v=07-QBnEkgXU",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "the-tru-man-show",
    tmdbId: 37165,
    title: "The Truman Show",
    tagline: "On the air. Unaware.",
    year: 1998,
    rating: 8.2,
    votes: "1.1M",
    duration: "1h 43m",
    genres: ["Comedy", "Drama"],
    director: "Peter Weir",
    cast: ["Jim Carrey", "Laura Linney", "Noah Emmerich", "Natascha McElhone", "Ed Harris"],
    description: "An insurance salesman discovers his whole life is actually a reality TV show.",
    fullOverview: "Truman Burbank is the star of 'The Truman Show', a 24-hour-a-day reality TV program that broadcasts every aspect of his life without his knowledge. His entire hometown is an enormous set and everyone around him is an actor.",
    poster: "https://image.tmdb.org/t/p/w500/vuza0WqY239yBXOadKlGwJsZJFE.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/8Z87f8K4Qh03xL9i94E3wNf0Qj9.jpg",
    trailerKey: "dlnmQbPGuls",
    trailerUrl: "https://www.youtube.com/watch?v=dlnmQbPGuls",
    trailerSource: "youtube",
    featured: false
  }
];

console.log(`Mega Catalog ready: ${megaCatalog.length} movies`);

