// Sci-Fi, Space & Fantasy Classics
export const scifiAndFantasyMovies = [
  {
    id: "the-lord-of-the-rings-the-fellowship-of-the-ring",
    tmdbId: 120,
    title: "The Lord of the Rings: The Fellowship of the Ring",
    tagline: "One ring to rule them all.",
    year: 2001,
    rating: 8.9,
    votes: "2.0M",
    duration: "2h 58m",
    genres: ["Adventure", "Fantasy", "Action"],
    director: "Peter Jackson",
    cast: ["Elijah Wood", "Ian McKellen", "Viggo Mortensen", "Sean Astin", "Orlando Bloom"],
    description: "A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring.",
    fullOverview: "Young hobbit Frodo Baggins, after inheriting a mysterious ring from his uncle Bilbo, must leave his home in order to keep it from falling into the hands of its evil creator, Dark Lord Sauron.",
    poster: "https://image.tmdb.org/t/p/w500/6oom5QYQ2yQTMJIbnvbkBL9cDK6.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/vRQnzOn4H106y3TyCrvl0ilSTjd.jpg",
    trailerKey: "V75dMMIW2B4",
    trailerUrl: "https://www.youtube.com/watch?v=V75dMMIW2B4",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "the-lord-of-the-rings-the-two-towers",
    tmdbId: 121,
    title: "The Lord of the Rings: The Two Towers",
    tagline: "A New Power Is Rising.",
    year: 2002,
    rating: 8.8,
    votes: "1.8M",
    duration: "2h 59m",
    genres: ["Adventure", "Fantasy", "Action"],
    director: "Peter Jackson",
    cast: ["Elijah Wood", "Ian McKellen", "Viggo Mortensen", "Sean Astin", "Andy Serkis"],
    description: "While Frodo and Sam edge closer to Mordor with the help of the shifty Gollum, the divided fellowship makes a stand against Sauron's new ally.",
    fullOverview: "Frodo Baggins and the other members of the Fellowship continue on their sacred quest to destroy the One Ring--but on separate paths. Their destinies lie at two towers -- Orthanc Citadel in Isengard and Barad-dûr in Mordor.",
    poster: "https://image.tmdb.org/t/p/w500/5VTN0pR8gcqV3EPUHHfMGnJYN9L.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/kWYfW2Re0rUDE6IHhyAkENuocPa.jpg",
    trailerKey: "LbfMDwc4azU",
    trailerUrl: "https://www.youtube.com/watch?v=LbfMDwc4azU",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "the-lord-of-the-rings-the-return-of-the-king",
    tmdbId: 122,
    title: "The Lord of the Rings: The Return of the King",
    tagline: "The Eye of the Enemy is moving.",
    year: 2003,
    rating: 9.0,
    votes: "2.0M",
    duration: "3h 21m",
    genres: ["Adventure", "Fantasy", "Action"],
    director: "Peter Jackson",
    cast: ["Elijah Wood", "Ian McKellen", "Viggo Mortensen", "Sean Astin", "Cate Blanchett"],
    description: "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom.",
    fullOverview: "Aragorn is revealed as the heir to the ancient kings as he, Gandalf and the other members of the broken fellowship struggle to save Gondor from Sauron's forces.",
    poster: "https://image.tmdb.org/t/p/w500/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/lXhgCODAbBXL5buk9yEmTFOo0B2.jpg",
    trailerKey: "r5X-hFf6Bwo",
    trailerUrl: "https://www.youtube.com/watch?v=r5X-hFf6Bwo",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "star-wars-a-new-hope",
    tmdbId: 11,
    title: "Star Wars: Episode IV - A New Hope",
    tagline: "A long time ago in a galaxy far, far away...",
    year: 1977,
    rating: 8.6,
    votes: "1.4M",
    duration: "2h 01m",
    genres: ["Sci-Fi", "Action", "Adventure"],
    director: "George Lucas",
    cast: ["Mark Hamill", "Harrison Ford", "Carrie Fisher", "Peter Cushing", "Alec Guinness"],
    description: "Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a Wookiee and two droids to save the galaxy.",
    fullOverview: "Princess Leia is captured and held hostage by the evil Imperial forces in their effort to take over the galactic Empire. Venturesome Luke Skywalker and dashing captain Han Solo team together with the loveable robot duo R2-D2 and C-3PO to rescue the beautiful princess.",
    poster: "https://image.tmdb.org/t/p/w500/6FfCtAuVAW8XJjZ7eWeLibRLWTw.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/zqkmTXzjkAgPnBSIODw5ro0w49M.jpg",
    trailerKey: "vZ734NWnAHA",
    trailerUrl: "https://www.youtube.com/watch?v=vZ734NWnAHA",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "star-wars-the-empire-strikes-back",
    tmdbId: 1891,
    title: "Star Wars: Episode V - The Empire Strikes Back",
    tagline: "The Adventure Continues...",
    year: 1980,
    rating: 8.7,
    votes: "1.3M",
    duration: "2h 04m",
    genres: ["Sci-Fi", "Action", "Adventure"],
    director: "Irvin Kershner",
    cast: ["Mark Hamill", "Harrison Ford", "Carrie Fisher", "Billy Dee Williams", "Frank Oz"],
    description: "After the Rebels are overpowered by the Empire, Luke Skywalker begins Jedi training with Yoda, while his friends are pursued across the galaxy.",
    fullOverview: "The epic adventure continues as the Empire prepares to launch an all-out assault against the Rebel Alliance, forcing our heroes to flee the frozen planet Hoth. Meanwhile, Luke seeks out the great Jedi Master Yoda.",
    poster: "https://image.tmdb.org/t/p/w500/nNAeTmF4CtdSgMDplXTDPOpYzsX.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/aJCtkxLLzkk1pEjk93rIQa9fGv5.jpg",
    trailerKey: "JNwNXF9Y6Qw",
    trailerUrl: "https://www.youtube.com/watch?v=JNwNXF9Y6Qw",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "jurassic-park",
    tmdbId: 329,
    title: "Jurassic Park",
    tagline: "An adventure 65 million years in the making.",
    year: 1993,
    rating: 8.2,
    votes: "1.1M",
    duration: "2h 07m",
    genres: ["Adventure", "Sci-Fi", "Thriller"],
    director: "Steven Spielberg",
    cast: ["Sam Neill", "Laura Dern", "Jeff Goldblum", "Richard Attenborough"],
    description: "A pragmatic paleontologist touring an almost complete theme park on an island in Central America is tasked with protecting a couple of kids after a power failure.",
    fullOverview: "A wealthy entrepreneur secretly creates a theme park featuring living dinosaurs drawn from prehistoric DNA. Before opening the attraction to the public, he invites a top paleontologist and paleobotanist.",
    poster: "https://image.tmdb.org/t/p/w500/oU7Oq2kFAAlGqbU4VoAE36g4hoI.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/lGhuP913H3H6XW3JgP9qP8k0M6.jpg",
    trailerKey: "lc0UehYemQA",
    trailerUrl: "https://www.youtube.com/watch?v=lc0UehYemQA",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "avatar",
    tmdbId: 19995,
    title: "Avatar",
    tagline: "Enter the world of Pandora.",
    year: 2009,
    rating: 7.9,
    votes: "1.4M",
    duration: "2h 42m",
    genres: ["Sci-Fi", "Action", "Adventure", "Fantasy"],
    director: "James Cameron",
    cast: ["Sam Worthington", "Zoe Saldaña", "Sigourney Weaver", "Stephen Lang", "Michelle Rodriguez"],
    description: "A paraplegic Marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.",
    fullOverview: "In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.",
    poster: "https://image.tmdb.org/t/p/w500/kyeqWdyUXW608qlYkRqosgbbJyK.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/vL5LR6WdxWPjCfa5qvLz3p5q0b4.jpg",
    trailerKey: "5PSNL1qE6VY",
    trailerUrl: "https://www.youtube.com/watch?v=5PSNL1qE6VY",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "avatar-the-way-of-water",
    tmdbId: 76600,
    title: "Avatar: The Way of Water",
    tagline: "Return to Pandora.",
    year: 2022,
    rating: 7.7,
    votes: "580K",
    duration: "3h 12m",
    genres: ["Sci-Fi", "Action", "Adventure"],
    director: "James Cameron",
    cast: ["Sam Worthington", "Zoe Saldaña", "Sigourney Weaver", "Stephen Lang", "Kate Winslet"],
    description: "Jake Sully lives with his newfound family formed on the extrasolar moon Pandora. Once a familiar threat returns, Jake must work with Neytiri and the army of the Na'vi.",
    fullOverview: "Set more than a decade after the events of the first film, learn the story of the Sully family (Jake, Neytiri, and their kids), the trouble that follows them, the lengths they go to keep each other safe.",
    poster: "https://image.tmdb.org/t/p/w500/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/s16H6tpK2utvwDtzZ8Qy4qm5Emw.jpg",
    trailerKey: "d9MyW72ELq0",
    trailerUrl: "https://www.youtube.com/watch?v=d9MyW72ELq0",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "alien",
    tmdbId: 348,
    title: "Alien",
    tagline: "In space no one can hear you scream.",
    year: 1979,
    rating: 8.5,
    votes: "950K",
    duration: "1h 57m",
    genres: ["Sci-Fi", "Horror"],
    director: "Ridley Scott",
    cast: ["Sigourney Weaver", "Tom Skerritt", "John Hurt", "Veronica Cartwright", "Harry Dean Stanton"],
    description: "The crew of a commercial spacecraft encounters a deadly lifeform after investigating an unknown transmission.",
    fullOverview: "During its return to the earth, commercial spaceship Nostromo intercepts a distress signal from a distant planet. When a team searches the telephone box, an extraterrestrial lifeform attacks one of them.",
    poster: "https://image.tmdb.org/t/p/w500/vfrQk5IPloGg1v9Rzbh2Eg3VGyM.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/AmR3JG1DYz5kbSczgPH2HNjTq64.jpg",
    trailerKey: "LjLamj-b0I8",
    trailerUrl: "https://www.youtube.com/watch?v=LjLamj-b0I8",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "aliens",
    tmdbId: 679,
    title: "Aliens",
    tagline: "This time it's war.",
    year: 1986,
    rating: 8.4,
    votes: "780K",
    duration: "2h 17m",
    genres: ["Action", "Sci-Fi", "Horror", "Thriller"],
    director: "James Cameron",
    cast: ["Sigourney Weaver", "Michael Biehn", "Carrie Henn", "Paul Reiser", "Bill Paxton"],
    description: "Decades after surviving the Nostromo incident, Ellen Ripley is sent out to re-establish contact with a terraforming colony.",
    fullOverview: "Ripley, the sole survivor of the Nostromo's deadly encounter with the monstrous Alien, returns to Earth after drifting through space in hypersleep for 57 years. She is sent with colonial marines to investigate LV-426.",
    poster: "https://image.tmdb.org/t/p/w500/r1x5AnYWWneFqEGND3nhv599429.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/8Z87f8K4Qh03xL9i94E3wNf0Qj9.jpg",
    trailerKey: "bTCaVKK1f_o",
    trailerUrl: "https://www.youtube.com/watch?v=bTCaVKK1f_o",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "terminator-2-judgment-day",
    tmdbId: 280,
    title: "Terminator 2: Judgment Day",
    tagline: "It's nothing personal.",
    year: 1991,
    rating: 8.6,
    votes: "1.2M",
    duration: "2h 17m",
    genres: ["Action", "Sci-Fi", "Thriller"],
    director: "James Cameron",
    cast: ["Arnold Schwarzenegger", "Linda Hamilton", "Edward Furlong", "Robert Patrick"],
    description: "A cyborg, identical to the one who failed to kill Sarah Connor, must now protect her ten-year-old son John from a more advanced cyborg.",
    fullOverview: "Set ten years after the events of the original, Sarah Connor’s ordeal is only just beginning as she struggles to protect her son John, the future leader of the human resistance against the machines.",
    poster: "https://image.tmdb.org/t/p/w500/5M0j0B18abtBI5vhRdx97ASm31b.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/8Z87f8K4Qh03xL9i94E3wNf0Qj9.jpg",
    trailerKey: "CRRlbK5w8AE",
    trailerUrl: "https://www.youtube.com/watch?v=CRRlbK5w8AE",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "the-terminator",
    tmdbId: 218,
    title: "The Terminator",
    tagline: "Your future is in his hands.",
    year: 1984,
    rating: 8.1,
    votes: "910K",
    duration: "1h 47m",
    genres: ["Action", "Sci-Fi"],
    director: "James Cameron",
    cast: ["Arnold Schwarzenegger", "Michael Biehn", "Linda Hamilton", "Paul Winfield"],
    description: "A human soldier is sent from 2029 to 1984 to stop an almost indestructible cyborg killing machine.",
    fullOverview: "A cyborg is sent from the future on a deadly mission: to kill Sarah Connor, a young woman whose life will have great significance in years to come. A human soldier is sent to protect her.",
    poster: "https://image.tmdb.org/t/p/w500/qvktm0BHcnmDpul4Hz01GIazWPr.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/8Z87f8K4Qh03xL9i94E3wNf0Qj9.jpg",
    trailerKey: "k64P4l2Wmeg",
    trailerUrl: "https://www.youtube.com/watch?v=k64P4l2Wmeg",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "the-martian",
    tmdbId: 286217,
    title: "The Martian",
    tagline: "Help is only 140 million miles away.",
    year: 2015,
    rating: 8.0,
    votes: "910K",
    duration: "2h 24m",
    genres: ["Drama", "Adventure", "Sci-Fi"],
    director: "Ridley Scott",
    cast: ["Matt Damon", "Jessica Chastain", "Kristen Wiig", "Jeff Daniels", "Michael Peña"],
    description: "An astronaut becomes stranded on Mars after his team assume him dead, and must rely on his ingenuity to signal to Earth.",
    fullOverview: "During a mission to Mars, American astronaut Mark Watney is presumed dead after a fierce storm and left behind by his crew. But Watney has survived and finds himself stranded and alone on the hostile planet.",
    poster: "https://image.tmdb.org/t/p/w500/5BHuvQ6p9kL0xG0967A8f8lM3wR.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/8Z87f8K4Qh03xL9i94E3wNf0Qj9.jpg",
    trailerKey: "ej3ioOneTy8",
    trailerUrl: "https://www.youtube.com/watch?v=ej3ioOneTy8",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "gravity",
    tmdbId: 49047,
    title: "Gravity",
    tagline: "Don't let go.",
    year: 2013,
    rating: 7.7,
    votes: "840K",
    duration: "1h 31m",
    genres: ["Sci-Fi", "Thriller", "Drama"],
    director: "Alfonso Cuarón",
    cast: ["Sandra Bullock", "George Clooney", "Ed Harris", "Orto Ignatiussen"],
    description: "Two astronauts work together to survive after an accident leaves them stranded in space.",
    fullOverview: "Dr. Ryan Stone, a brilliant medical engineer on her first shuttle mission, with veteran astronaut Matt Kowalsky in command of his last flight before retiring. But on a seemingly routine spacewalk, disaster strikes.",
    poster: "https://image.tmdb.org/t/p/w500/49WJfeN0moxb9IPfGn8AIqMGskD.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/8Z87f8K4Qh03xL9i94E3wNf0Qj9.jpg",
    trailerKey: "OiTiKOy59o4",
    trailerUrl: "https://www.youtube.com/watch?v=OiTiKOy59o4",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "ex-machina",
    tmdbId: 264660,
    title: "Ex Machina",
    tagline: "There is nothing more human than the will to survive.",
    year: 2014,
    rating: 7.7,
    votes: "580K",
    duration: "1h 48m",
    genres: ["Sci-Fi", "Drama", "Thriller"],
    director: "Alex Garland",
    cast: ["Domhnall Gleeson", "Alicia Vikander", "Oscar Isaac", "Sonoya Mizuno"],
    description: "A young programmer is selected to participate in a ground-breaking experiment in synthetic intelligence by evaluating the human qualities of a humanoid A.I.",
    fullOverview: "Caleb, a 26 year old coder at the world's largest internet company, wins a competition to spend a week at a private mountain retreat belonging to Nathan, the reclusive CEO of the company.",
    poster: "https://image.tmdb.org/t/p/w500/btbRB7BrD887994982kY5r78w2.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/8Z87f8K4Qh03xL9i94E3wNf0Qj9.jpg",
    trailerKey: "bggUmgeMCdc",
    trailerUrl: "https://www.youtube.com/watch?v=bggUmgeMCdc",
    trailerSource: "youtube",
    featured: false
  }
];
