import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, '..');

// Import original 16
import { originalMovies } from './seed-base.mjs';

// We will build a total of 220+ movies
const additionalMovies = [
  // 1. Classic Drama & Crime
  {
    id: "the-shawshank-redemption",
    tmdbId: 278,
    title: "The Shawshank Redemption",
    tagline: "Fear can hold you prisoner. Hope can set you free.",
    year: 1994,
    rating: 9.3,
    votes: "2.8M",
    duration: "2h 22m",
    genres: ["Drama", "Crime"],
    director: "Frank Darabont",
    cast: ["Tim Robbins", "Morgan Freeman", "Bob Gunton", "William Sadler"],
    description: "A banker convicted of uxoricide forms a friendship over a quarter of a century with a hardened convict.",
    fullOverview: "Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden.",
    poster: "https://image.tmdb.org/t/p/w500/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg",
    trailerKey: "PLl99DlL6b4",
    trailerUrl: "https://www.youtube.com/watch?v=PLl99DlL6b4",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "the-godfather",
    tmdbId: 238,
    title: "The Godfather",
    tagline: "An offer you can't refuse.",
    year: 1972,
    rating: 9.2,
    votes: "2.0M",
    duration: "2h 55m",
    genres: ["Drama", "Crime"],
    director: "Francis Ford Coppola",
    cast: ["Marlon Brando", "Al Pacino", "James Caan", "Robert Duvall", "Diane Keaton"],
    description: "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
    fullOverview: "Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers.",
    poster: "https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/tmU7GeKVybMWFButWEGl2M4GeiP.jpg",
    trailerKey: "UaVTIH8mujA",
    trailerUrl: "https://www.youtube.com/watch?v=UaVTIH8mujA",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "the-godfather-part-ii",
    tmdbId: 240,
    title: "The Godfather Part II",
    tagline: "All the power on earth can't change destiny.",
    year: 1974,
    rating: 9.0,
    votes: "1.4M",
    duration: "3h 22m",
    genres: ["Drama", "Crime"],
    director: "Francis Ford Coppola",
    cast: ["Al Pacino", "Robert De Niro", "Robert Duvall", "Diane Keaton", "John Cazale"],
    description: "The early life and career of Vito Corleone in 1920s New York City is portrayed, while his son expands the family syndicate.",
    fullOverview: "In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.",
    poster: "https://image.tmdb.org/t/p/w500/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/kGzFbGhp99zva6oZODqw5x6G2um.jpg",
    trailerKey: "9O1Iy9od7-A",
    trailerUrl: "https://www.youtube.com/watch?v=9O1Iy9od7-A",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "fight-club",
    tmdbId: 550,
    title: "Fight Club",
    tagline: "Mischief. Mayhem. Soap.",
    year: 1999,
    rating: 8.8,
    votes: "2.3M",
    duration: "2h 19m",
    genres: ["Drama", "Thriller"],
    director: "David Fincher",
    cast: ["Edward Norton", "Brad Pitt", "Helena Bonham Carter", "Meat Loaf"],
    description: "An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into something much more.",
    fullOverview: "A ticking-time-bomb insomniac and a slippery soap salesman channel primal male aggression into a shocking new form of therapy. Their concept catches on, with underground 'fight clubs' forming in every town, until an eccentric gets in the way.",
    poster: "https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/hZkgoQYus5vegHoetLkCJzb17zJ.jpg",
    trailerKey: "qtRKDV93JU8",
    trailerUrl: "https://www.youtube.com/watch?v=qtRKDV93JU8",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "forrest-gump",
    tmdbId: 13,
    title: "Forrest Gump",
    tagline: "The world will never be the same once you've seen it through the eyes of Forrest Gump.",
    year: 1994,
    rating: 8.8,
    votes: "2.2M",
    duration: "2h 22m",
    genres: ["Comedy", "Drama", "Romance"],
    director: "Robert Zemeckis",
    cast: ["Tom Hanks", "Robin Wright", "Gary Sinise", "Sally Field"],
    description: "The history of the United States from the 1950s to the '70s unfolds from the perspective of an Alabama man with an IQ of 75.",
    fullOverview: "A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. Yet, despite all the things he has attained, his one true love eludes him.",
    poster: "https://image.tmdb.org/t/p/w500/arw2VCBveWOVZr6pxd9XTd1TdQa.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/qdIMIH4WrJT250xAUz9qAHxXJxu.jpg",
    trailerKey: "bLvqoHBptjg",
    trailerUrl: "https://www.youtube.com/watch?v=bLvqoHBptjg",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "goodfellas",
    tmdbId: 769,
    title: "GoodFellas",
    tagline: "Three Decades of Life in the Mafia.",
    year: 1990,
    rating: 8.7,
    votes: "1.3M",
    duration: "2h 25m",
    genres: ["Drama", "Crime", "Biography"],
    director: "Martin Scorsese",
    cast: ["Robert De Niro", "Ray Liotta", "Joe Pesci", "Lorraine Bracco", "Paul Sorvino"],
    description: "The story of Henry Hill and his life in the mafia, covering his relationship with his wife and his mob partners.",
    fullOverview: "The true story of Henry Hill, a half-Irish, half-Sicilian Brooklyn kid who is adopted by neighbourhood gangsters at an early age and climbs the ranks of a Mafia family under the guidance of Jimmy Conway.",
    poster: "https://image.tmdb.org/t/p/w500/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/sw7mordbZxgITU877hTpJ9ubdo4.jpg",
    trailerKey: "qo5jJpHtI1Y",
    trailerUrl: "https://www.youtube.com/watch?v=qo5jJpHtI1Y",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "the-departed",
    tmdbId: 1422,
    title: "The Departed",
    tagline: "Lies. Betrayal. Sacrifice. How far will you take it?",
    year: 2006,
    rating: 8.5,
    votes: "1.4M",
    duration: "2h 31m",
    genres: ["Drama", "Crime", "Thriller"],
    director: "Martin Scorsese",
    cast: ["Leonardo DiCaprio", "Matt Damon", "Jack Nicholson", "Mark Wahlberg", "Martin Sheen"],
    description: "An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in South Boston.",
    fullOverview: "To take down South Boston's Irish Mafia, the police send in one of their own to infiltrate the underworld, not realizing the syndicate has done likewise. While an undercover cop curries favor with the mob kingpin, a career criminal rises through the police ranks.",
    poster: "https://image.tmdb.org/t/p/w500/nT97ifVT2J1yMQmeq20Qblg61T.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/7k4Ta74abLgkd5vj9b92yC2XQpE.jpg",
    trailerKey: "iojhqm0JTW4",
    trailerUrl: "https://www.youtube.com/watch?v=iojhqm0JTW4",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "se7en",
    tmdbId: 807,
    title: "Se7en",
    tagline: "Seven deadly sins. Seven ways to die.",
    year: 1995,
    rating: 8.6,
    votes: "1.8M",
    duration: "2h 07m",
    genres: ["Crime", "Mystery", "Drama", "Thriller"],
    director: "David Fincher",
    cast: ["Brad Pitt", "Morgan Freeman", "Gwyneth Paltrow", "Kevin Spacey"],
    description: "Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.",
    fullOverview: "Two homicide detectives are on a desperate hunt for a serial killer whose crimes are based on the 'seven deadly sins'. The seasoned Det. Sommerset researches each sin in an effort to get inside the killer's mind, while his novice partner, Mills, scoffs at his efforts.",
    poster: "https://image.tmdb.org/t/p/w500/6yoghtyTBoPudoMyqlmp0ur4jvU.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/ba4Vu0cdV84aV3DjNO4dUJa615p.jpg",
    trailerKey: "znmZoVkCjpI",
    trailerUrl: "https://www.youtube.com/watch?v=znmZoVkCjpI",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "the-silence-of-the-lambs",
    tmdbId: 274,
    title: "The Silence of the Lambs",
    tagline: "To enter the mind of a killer she must challenge the mind of a madman.",
    year: 1991,
    rating: 8.6,
    votes: "1.5M",
    duration: "1h 58m",
    genres: ["Crime", "Drama", "Thriller", "Horror"],
    director: "Jonathan Demme",
    cast: ["Jodie Foster", "Anthony Hopkins", "Scott Glenn", "Ted Levine"],
    description: "A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer.",
    fullOverview: "Clarice Starling is a top student at the FBI's training academy. Jack Crawford wants Clarice to interview Dr. Hannibal Lecter, a brilliant psychiatrist who is also a violent psychopath, serving life behind bars for various acts of murder and cannibalism.",
    poster: "https://image.tmdb.org/t/p/w500/uS9m8OBk1A8eM9I042bx8XXpqAq.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/mfwq2nMBz1bLLLCmnY0xPtGQ49e.jpg",
    trailerKey: "W6Mm8Sbe__o",
    trailerUrl: "https://www.youtube.com/watch?v=W6Mm8Sbe__o",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "schindlers-list",
    tmdbId: 424,
    title: "Schindler's List",
    tagline: "Whoever saves one life, saves the world entire.",
    year: 1993,
    rating: 9.0,
    votes: "1.4M",
    duration: "3h 15m",
    genres: ["Drama", "History", "Biography"],
    director: "Steven Spielberg",
    cast: ["Liam Neeson", "Ben Kingsley", "Ralph Fiennes", "Caroline Goodall"],
    description: "In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce.",
    fullOverview: "The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.",
    poster: "https://image.tmdb.org/t/p/w500/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/zb6fM1CX41D9r69hdYVhBhYmQdm.jpg",
    trailerKey: "gG22XNhtnoY",
    trailerUrl: "https://www.youtube.com/watch?v=gG22XNhtnoY",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "saving-private-ryan",
    tmdbId: 857,
    title: "Saving Private Ryan",
    tagline: "The mission is a man.",
    year: 1998,
    rating: 8.6,
    votes: "1.5M",
    duration: "2h 49m",
    genres: ["Drama", "History", "Action"],
    director: "Steven Spielberg",
    cast: ["Tom Hanks", "Matt Damon", "Tom Sizemore", "Edward Burns", "Vin Diesel"],
    description: "Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper whose brothers have been killed.",
    fullOverview: "As U.S. troops storm the beaches of Normandy, three brothers lie dead on the battlefield, with a fourth trapped behind enemy lines. Ranger captain John Miller and seven men are tasked with penetrating German-held territory and bringing the boy home.",
    poster: "https://image.tmdb.org/t/p/w500/uqx37cS8cpHg8x35f9U5IBlrCV3.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/bdD39UpWhOus89fvdgtX2KqJ9Tq.jpg",
    trailerKey: "zwhP5b4tDkg",
    trailerUrl: "https://www.youtube.com/watch?v=zwhP5b4tDkg",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "the-prestige",
    tmdbId: 1124,
    title: "The Prestige",
    tagline: "Are you watching closely?",
    year: 2006,
    rating: 8.5,
    votes: "1.4M",
    duration: "2h 10m",
    genres: ["Drama", "Mystery", "Sci-Fi", "Thriller"],
    director: "Christopher Nolan",
    cast: ["Hugh Jackman", "Christian Bale", "Michael Caine", "Scarlett Johansson", "David Bowie"],
    description: "After a tragic accident, two stage magicians in 1890s London engage in a battle to create the ultimate illusion.",
    fullOverview: "A mysterious story of two magicians whose intense rivalry leads them on a life-long battle for supremacy -- full of obsession, deceit and jealousy with dangerous and deadly consequences.",
    poster: "https://image.tmdb.org/t/p/w500/tRNlZbgNCNOpLpbPEz5L8G8A0JN.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/meR207V2TqW2tX5w1W3h49X7A5l.jpg",
    trailerKey: "o4gHCmTQDVI",
    trailerUrl: "https://www.youtube.com/watch?v=o4gHCmTQDVI",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "memento",
    tmdbId: 77,
    title: "Memento",
    tagline: "Some memories are best forgotten.",
    year: 2000,
    rating: 8.4,
    votes: "1.3M",
    duration: "1h 53m",
    genres: ["Mystery", "Thriller"],
    director: "Christopher Nolan",
    cast: ["Guy Pearce", "Carrie-Anne Moss", "Joe Pantoliano", "Mark Boone Junior"],
    description: "A man with short-term memory loss attempts to track down his wife's murderer using photographs and tattoos.",
    fullOverview: "Leonard Shelby is tracking down the man who raped and murdered his wife. The difficulty of locating his wife's killer, however, is compounded by the fact that he suffers from a rare, untreatable form of short term memory loss.",
    poster: "https://image.tmdb.org/t/p/w500/yuNs09hvpHVU1cBTCA99x5w267K.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/5kJ9rJ9k811o0f8w97s5g51vY.jpg",
    trailerKey: "0vS0E9bBS74",
    trailerUrl: "https://www.youtube.com/watch?v=0vS0E9bBS74",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "shutter-island",
    tmdbId: 11324,
    title: "Shutter Island",
    tagline: "Someone is missing.",
    year: 2010,
    rating: 8.2,
    votes: "1.4M",
    duration: "2h 18m",
    genres: ["Drama", "Mystery", "Thriller"],
    director: "Martin Scorsese",
    cast: ["Leonardo DiCaprio", "Mark Ruffalo", "Ben Kingsley", "Max von Sydow", "Michelle Williams"],
    description: "In 1954, a U.S. Marshal investigates the disappearance of a murderer who escaped from a hospital for the criminally insane.",
    fullOverview: "World War II soldier-turned-U.S. Marshal Teddy Daniels investigates the disappearance of a patient from Boston's Shutter Island Ashecliffe Hospital. He's been pushing for an assignment on the island for personal reasons, but before long he wonders whether he hasn't been brought there as part of a twisted plot.",
    poster: "https://image.tmdb.org/t/p/w500/4GDy0PHYX3VRXUtwK5996Jn3gpH.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/578j85D10yW0X8y2hBf05lM84z.jpg",
    trailerKey: "5iaYLCiq5RM",
    trailerUrl: "https://www.youtube.com/watch?v=5iaYLCiq5RM",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "the-wolf-of-wall-street",
    tmdbId: 106646,
    title: "The Wolf of Wall Street",
    tagline: "EARN. SPEND. PARTY.",
    year: 2013,
    rating: 8.2,
    votes: "1.5M",
    duration: "3h 00m",
    genres: ["Crime", "Drama", "Comedy", "Biography"],
    director: "Martin Scorsese",
    cast: ["Leonardo DiCaprio", "Jonah Hill", "Margot Robbie", "Matthew McConaughey", "Kyle Chandler"],
    description: "Based on the true story of Jordan Belfort, from his rise to a wealthy stock-broker to his fall involving crime and corruption.",
    fullOverview: "A New York stockbroker refuses to cooperate in a large securities fraud case involving corruption on Wall Street, corporate banking world and mob infiltration. Based on Jordan Belfort's autobiography.",
    poster: "https://image.tmdb.org/t/p/w500/pWHf4khOloNVfSw8RQI4cG9bW98.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/7n2Gz5aK8A2P2o18WqF9f0P1oG7.jpg",
    trailerKey: "iszwuX1AK6A",
    trailerUrl: "https://www.youtube.com/watch?v=iszwuX1AK6A",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "django-unchained",
    tmdbId: 68718,
    title: "Django Unchained",
    tagline: "Life, liberty and the pursuit of vengeance.",
    year: 2012,
    rating: 8.5,
    votes: "1.6M",
    duration: "2h 45m",
    genres: ["Western", "Drama", "Action"],
    director: "Quentin Tarantino",
    cast: ["Jamie Foxx", "Christoph Waltz", "Leonardo DiCaprio", "Kerry Washington", "Samuel L. Jackson"],
    description: "With the help of a German bounty hunter, a freed slave sets out to rescue his wife from a brutal Mississippi plantation owner.",
    fullOverview: "With the help of a German bounty-hunter, a freed slave sets out to rescue his wife from a brutal plantation owner in Mississippi.",
    poster: "https://image.tmdb.org/t/p/w500/7oWY8vdWW7thTzWh3OKYRkWUlD5.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/2o0lWq5f4eG9K6V5lT4eX8rP3sD.jpg",
    trailerKey: "0fUCuvNlOCg",
    trailerUrl: "https://www.youtube.com/watch?v=0fUCuvNlOCg",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "inglourious-basterds",
    tmdbId: 16869,
    title: "Inglourious Basterds",
    tagline: "Once upon a time in Nazi occupied France...",
    year: 2009,
    rating: 8.4,
    votes: "1.5M",
    duration: "2h 33m",
    genres: ["Drama", "Action", "Thriller", "War"],
    director: "Quentin Tarantino",
    cast: ["Brad Pitt", "Mélanie Laurent", "Christoph Waltz", "Eli Roth", "Michael Fassbender"],
    description: "In Nazi-occupied France during World War II, a plan to assassinate Nazi leaders by a group of Jewish U.S. soldiers coincides with a theatre owner's revenge plan.",
    fullOverview: "In Nazi-occupied France during World War II, a group of Jewish-American soldiers known as 'The Basterds' are chosen specifically to spread fear throughout the Third Reich by scalping and brutally murdering Nazis.",
    poster: "https://image.tmdb.org/t/p/w500/7sfbEnaARXDDhKm0CZ7D7uc2sbo.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/8Z87f8K4Qh03xL9i94E3wNf0Qj9.jpg",
    trailerKey: "KnrRy6kSFF0",
    trailerUrl: "https://www.youtube.com/watch?v=KnrRy6kSFF0",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "no-country-for-old-men",
    tmdbId: 6977,
    title: "No Country for Old Men",
    tagline: "There are no clean getaways.",
    year: 2007,
    rating: 8.2,
    votes: "1.0M",
    duration: "2h 02m",
    genres: ["Crime", "Drama", "Thriller"],
    director: "Joel Coen, Ethan Coen",
    cast: ["Tommy Lee Jones", "Javier Bardem", "Josh Brolin", "Woody Harrelson", "Kelly Macdonald"],
    description: "Violence and mayhem ensue after a hunter stumbles upon a drug deal gone wrong and more than two million dollars in cash.",
    fullOverview: "Llewelyn Moss stumbles upon dead bodies, $2 million and a hoard of heroin in a Texas desert, but methodical killer Anton Chigurh comes looking for it, with local sheriff Ed Tom Bell hot on his trail.",
    poster: "https://image.tmdb.org/t/p/w500/6d5XOczV8oFiqBcxZ4VvO6h9pI1.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/x2O8P2Y2bX1q7W5h1v4P4R2P1V7.jpg",
    trailerKey: "38A__WT3-o0",
    trailerUrl: "https://www.youtube.com/watch?v=38A__WT3-o0",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "there-will-be-blood",
    tmdbId: 7345,
    title: "There Will Be Blood",
    tagline: "When ambition meets faith.",
    year: 2007,
    rating: 8.2,
    votes: "620K",
    duration: "2h 38m",
    genres: ["Drama", "History"],
    director: "Paul Thomas Anderson",
    cast: ["Daniel Day-Lewis", "Paul Dano", "Kevin J. O'Connor", "Ciarán Hinds"],
    description: "A story of family, religion, hatred, oil and madness, focusing on a turn-of-the-century prospector in the early days of the business.",
    fullOverview: "Ruthless silver miner turned oil prospector Daniel Plainview moves to oil-rich California. Using his adopted son HW to project a trustworthy, family-man image, Plainview buys up local oil rights at bargain prices.",
    poster: "https://image.tmdb.org/t/p/w500/fa0RDkAlCec0ST2v5ElBgBv1RGe.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/8Z87f8K4Qh03xL9i94E3wNf0Qj9.jpg",
    trailerKey: "FeSLPELpMeM",
    trailerUrl: "https://www.youtube.com/watch?v=FeSLPELpMeM",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "the-social-network",
    tmdbId: 37799,
    title: "The Social Network",
    tagline: "You don't get to 500 million friends without making a few enemies.",
    year: 2010,
    rating: 7.8,
    votes: "750K",
    duration: "2h 00m",
    genres: ["Biography", "Drama", "History"],
    director: "David Fincher",
    cast: ["Jesse Eisenberg", "Andrew Garfield", "Justin Timberlake", "Armie Hammer", "Rooney Mara"],
    description: "As Harvard student Mark Zuckerberg creates the social networking site that would become known as Facebook, he is sued by the twins who claimed he stole their idea.",
    fullOverview: "On a fall night in 2003, Harvard undergrad and computer programming whiz Mark Zuckerberg sits down at his computer and heatedly begins working on a new idea.",
    poster: "https://image.tmdb.org/t/p/w500/n0ybibhJtQ5icDqTpTzbpHignAP.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/h9u3Qe9z5f5hG7R7P9x1M7g3V8K.jpg",
    trailerKey: "lB95KLmpLR4",
    trailerUrl: "https://www.youtube.com/watch?v=lB95KLmpLR4",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "gone-girl",
    tmdbId: 210577,
    title: "Gone Girl",
    tagline: "You don't know what you've got 'til it's...",
    year: 2014,
    rating: 8.1,
    votes: "1.0M",
    duration: "2h 29m",
    genres: ["Mystery", "Thriller", "Drama"],
    director: "David Fincher",
    cast: ["Ben Affleck", "Rosamund Pike", "Neil Patrick Harris", "Tyler Perry", "Carrie Coon"],
    description: "With his wife's disappearance having become the focus of an intense media circus, a man sees the spotlight turned on him when it's suspected that he may not be innocent.",
    fullOverview: "With his wife's disappearance having become the focus of an intense media circus, a man sees the spotlight turned on him when it's suspected that he may not be innocent.",
    poster: "https://image.tmdb.org/t/p/w500/qymaJhucquUwjpAC3GBWqQXENcq.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/p4pYqf10fJ9kK4eX8rP3sD.jpg",
    trailerKey: "2-_-1nJf8Vg",
    trailerUrl: "https://www.youtube.com/watch?v=2-_-1nJf8Vg",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "zodiac",
    tmdbId: 1949,
    title: "Zodiac",
    tagline: "There's more than one way to lose your life to a killer.",
    year: 2007,
    rating: 7.7,
    votes: "580K",
    duration: "2h 37m",
    genres: ["Crime", "Drama", "Mystery", "Thriller"],
    director: "David Fincher",
    cast: ["Jake Gyllenhaal", "Mark Ruffalo", "Robert Downey Jr.", "Anthony Edwards", "Brian Cox"],
    description: "Between 1968 and 1983, a San Francisco cartoonist becomes an amateur detective obsessed with tracking down the Zodiac Killer.",
    fullOverview: "A cartoonist, a reporter and a pair of cops investigate the San Francisco Bay Area's notorious Zodiac Killer in this true-crime thriller.",
    poster: "https://image.tmdb.org/t/p/w500/6YVvs2qWz0hXf4Q4r4P1X4kY9X0.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/8Z87f8K4Qh03xL9i94E3wNf0Qj9.jpg",
    trailerKey: "yNncHPl1UXg",
    trailerUrl: "https://www.youtube.com/watch?v=yNncHPl1UXg",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "prisoners",
    tmdbId: 146233,
    title: "Prisoners",
    tagline: "Every moment matters.",
    year: 2013,
    rating: 8.1,
    votes: "780K",
    duration: "2h 33m",
    genres: ["Drama", "Mystery", "Thriller", "Crime"],
    director: "Denis Villeneuve",
    cast: ["Hugh Jackman", "Jake Gyllenhaal", "Viola Davis", "Maria Bello", "Paul Dano"],
    description: "When Keller Dover's daughter and her friend go missing, he takes matters into his own hands as the police pursue multiple leads.",
    fullOverview: "When Keller Dover's six-year-old daughter, Anna, is missing, along with her friend, Joy, his only lead is a dilapidated RV that had earlier been parked on their street.",
    poster: "https://image.tmdb.org/t/p/w500/tuZhZ6biFMrBGs847b2w9q9Gz8L.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/9l9f9k0K8A2P2o18WqF9f0P1oG7.jpg",
    trailerKey: "bpXfcT61YvM",
    trailerUrl: "https://www.youtube.com/watch?v=bpXfcT61YvM",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "sicario",
    tmdbId: 273481,
    title: "Sicario",
    tagline: "The boundary between order and chaos is where they operate.",
    year: 2015,
    rating: 7.7,
    votes: "490K",
    duration: "2h 01m",
    genres: ["Action", "Crime", "Drama", "Thriller"],
    director: "Denis Villeneuve",
    cast: ["Emily Blunt", "Benicio del Toro", "Josh Brolin", "Victor Garber", "Jon Bernthal"],
    description: "An idealistic FBI agent is enlisted by a government task force to aid in the escalating war against drugs at the border area between the U.S. and Mexico.",
    fullOverview: "An idealistic FBI agent is enlisted by a government task force to aid in the escalating war against drugs at the border area between the U.S. and Mexico.",
    poster: "https://image.tmdb.org/t/p/w500/pE0gL5d133p86j0Q2xW01oM02Gz.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/h9u3Qe9z5f5hG7R7P9x1M7g3V8K.jpg",
    trailerKey: "G8tlE7QQgW4",
    trailerUrl: "https://www.youtube.com/watch?v=G8tlE7QQgW4",
    trailerSource: "youtube",
    featured: false
  },
  {
    id: "arrival",
    tmdbId: 329865,
    title: "Arrival",
    tagline: "Why are they here?",
    year: 2016,
    rating: 8.0,
    votes: "740K",
    duration: "1h 56m",
    genres: ["Sci-Fi", "Drama", "Mystery"],
    director: "Denis Villeneuve",
    cast: ["Amy Adams", "Jeremy Renner", "Forest Whitaker", "Michael Stuhlbarg"],
    description: "A linguist works with the military to communicate with alien lifeforms after twelve mysterious spacecraft appear around the world.",
    fullOverview: "Taking place after alien crafts land around the world, an expert linguist is recruited by the military to determine whether they come in peace or are a threat.",
    poster: "https://image.tmdb.org/t/p/w500/x2FJsf1ElAgr63Y3PNPtJrcmpoe.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/9BBTo63ANSmhC4e6r62OJFuK2GL.jpg",
    trailerKey: "tFMo3UJ4B4g",
    trailerUrl: "https://www.youtube.com/watch?v=tFMo3UJ4B4g",
    trailerSource: "youtube",
    featured: false
  }
];

console.log(`Curated batch 2 ready: ${additionalMovies.length} movies`);
export { additionalMovies };
